reearth/reearth-flow

README.md
=> chore: modify README

Makefile.toml, README.md
- Fix settings for cargo make
- Organized each task in the makefile
=> chore: modify makefile for cargo make

.github/workflows/deny.yml, .github/workflows/dependencies.yml, Cargo.toml, deny.toml
- add cargo deny and cargo update workflow
- add cargo deny setting file
- cargo deny github actions workflow
- cargo update github actions workflow
=> chore: add cargo deny and cargo update workflow

.editorconfig, .github/workflows/ci.yml, Cargo.lock, Cargo.toml, crates/telemetry/Cargo.toml, crates/telemetry/src/lib.rs, crates/telemetry/src/logging.rs, crates/workflow/Cargo.toml, crates/workflow/src/action.rs, crates/workflow/src/error.rs, crates/workflow/src/graph.rs, crates/workflow/src/id.rs, crates/workflow/src/lib.rs, crates/workflow/src/workflow.rs, rustfmt.toml
- add workflow crate
- create workflow type definitions
- unit test
=> feat: add workflow-related type definitions

Cargo.lock, Cargo.toml, crates/common/Cargo.toml, crates/common/src/fs.rs, crates/common/src/lib.rs, crates/common/src/uri.rs, crates/storage/Cargo.toml, crates/storage/src/lib.rs, crates/storage/src/operator.rs, crates/storage/src/resolver.rs, crates/storage/src/storage.rs, deny.toml, rustfmt.toml
- add storage crate
- create storage layer
- unit testing
=> feat: add storage crate

crates/common/src/uri.rs, crates/storage/src/operator.rs, crates/storage/src/resolver.rs, crates/storage/src/storage.rs
- modify list function for storage
- Remove unused methods for uri and Storage
- Change the return value of the List method
=> feat: modify list function for storage

Cargo.toml
=> chore: bump cargo crates

Cargo.lock, Cargo.toml, crates/common/Cargo.toml, crates/workflow-runner/Cargo.toml, crates/workflow-runner/src/graph.rs, crates/workflow-runner/src/lib.rs, crates/workflow/src/action.rs, crates/workflow/src/graph.rs
- create execute graph
- add petgraph create
- create execute graph
=> feat: add execute graph for workflow-runner crate

Cargo.lock, Cargo.toml, crates/action/Cargo.toml, crates/action/src/action.rs, crates/action/src/lib.rs, crates/workflow-runner/src/graph.rs, crates/workflow-runner/src/job.rs, crates/workflow-runner/src/lib.rs, crates/workflow/src/action.rs, crates/workflow/src/graph.rs, crates/workflow/src/lib.rs, crates/workflow/src/workflow.rs
- add action and job modules
- add action module
- add job module
=> feat: add action and job modules

Cargo.lock, crates/action/Cargo.toml, crates/action/src/action.rs, crates/action/src/feature_reader.rs, crates/common/src/uri.rs, crates/storage/src/lib.rs, crates/storage/src/operator.rs, crates/workflow-runner/src/dag/execution_dag.rs
- modify feature reader module
- Add feature reader implementation
=> feat: modify feature reader module

crates/action/src/action.rs, crates/action/src/attribute_keeper.rs, crates/action/src/lib.rs, crates/workflow-runner/src/dag/dag_impl.rs, crates/workflow-runner/src/dag/execution_dag.rs
- add attributeKeeper action and implement its functionality
- add attributeKeeper action
=> feat: add attributeKeeper action and implement its functionality

crates/action/src/action.rs, crates/action/src/attribute_keeper.rs, crates/action/src/feature_reader.rs, crates/action/src/feature_writer.rs, crates/action/src/lib.rs, crates/storage/src/operator.rs, crates/workflow-runner/src/dag/execution_dag.rs
- add feature_writer module and implement featureWriter action
- create feature_writer module
=> feat: add feature_writer module and implement featureWriter action

Cargo.lock, Cargo.toml, crates/telemetry/Cargo.toml
=> chore(deps): weekly cargo update

.editorconfig, Cargo.lock, Cargo.toml, crates/cli/Cargo.toml, crates/cli/src/cli.rs, crates/cli/src/lib.rs, crates/cli/src/logger.rs, crates/cli/src/main.rs, crates/cli/src/run.rs, crates/workflow-runner/src/dag.rs, crates/workflow-runner/src/dag/execution_dag.rs, crates/workflow/src/workflow.rs
- add cli crate
- create run command
=> feat: add cli crate

crates/action/src/file_reader/csv.rs
- add offset option to CsvPropertySchema
- update csv reader
=> feat: add offset option to CsvPropertySchema

crates/action/src/attribute_keeper.rs, crates/action/src/file_reader/base.rs, crates/action/src/file_writer.rs, crates/cli/src/cli.rs, crates/storage/src/operator.rs
- modify logging statements to use debug level
=> chore: modify logging statements to use debug level

Cargo.lock, Cargo.toml, crates/eval-expr/Cargo.toml, crates/eval-expr/src/engine.rs, crates/eval-expr/src/error.rs, crates/eval-expr/src/lib.rs, crates/eval-expr/src/module.rs, crates/eval-expr/src/module/env.rs, crates/eval-expr/src/scope.rs, crates/eval-expr/src/utils.rs, crates/storage/src/operator.rs
- add eval-expr module and dependencies
- create eval expr module
- bump cargo.toml
=> feat: add eval-expr module and dependencies

Cargo.lock, crates/action/Cargo.toml, crates/action/src/action.rs, crates/action/src/attribute_filter.rs, crates/action/src/lib.rs, crates/common/Cargo.toml, crates/common/src/str.rs, crates/eval-expr/src/engine.rs, crates/eval-expr/src/lib.rs, crates/eval-expr/src/scope.rs, crates/workflow-runner/Cargo.toml, crates/workflow-runner/src/dag/execution_dag.rs
- add dependencies and modules, update scope
- create attribute filter
- add dependencies
- update scope
=> feat: add dependencies and modules, update scope

crates/action/src/action.rs, crates/action/src/attribute_merger.rs, crates/action/src/lib.rs
- add attributeMerger action implementation
- implement attribute merger
=> feat: add attributeMerger action implementation

crates/workflow-runner/src/dag/execution_dag.rs
- refactor expression engine cloning in execution_dag
=> chore: refactor expression engine cloning in execution_dag

Cargo.lock, Cargo.toml, crates/cli/Cargo.toml
=> chore: bump dependencies versions

Cargo.lock, Cargo.toml, crates/action/Cargo.toml, crates/action/src/action.rs, crates/action/src/attribute_filter.rs, crates/action/src/attribute_keeper.rs, crates/action/src/attribute_manager.rs, crates/action/src/attribute_manager/run.rs, crates/action/src/file_reader/csv.rs, crates/action/src/file_reader/run.rs, crates/action/src/file_reader/text.rs, crates/action/src/lib.rs, crates/eval-expr/Cargo.toml
- add attribute_manager module and update dependencies
- create attribute manager module
- bump dependencies
=> feat: add attribute_manager module and update dependencies

crates/action/src/attribute_filter.rs, crates/action/src/attribute_manager/run.rs
- refactor attribute filtering and attribute manager
- refactor attribute filter
- refactor attribute manager
=> chore: refactor attribute filtering and attribute manager

crates/action/src/action.rs, crates/action/src/attribute_aggregator.rs, crates/action/src/attribute_filter.rs, crates/action/src/attribute_keeper.rs, crates/action/src/attribute_merger.rs, crates/action/src/file_reader/runner.rs, crates/action/src/file_writer.rs, crates/action/src/lib.rs
- add attributeAggregator action and implement partial ordering for ActionValue
- add attributeAggregator action 
- implement partial ordering for ActionValue
=> feat: add attributeAggregator action and implement partial ordering for ActionValue

crates/action/src/attribute_merger.rs
- refactor join logic in attribute_merger
- refactor join logic in attribute_merger
=> chore: refactor join logic in attribute_merger

crates/action/src/attribute_filter.rs, crates/action/src/attribute_manager/runner.rs
- refactor attribute filtering and renaming logic
- refactor attribute filtering and renaming logic
=> chore: refactor attribute filtering and renaming logic

Cargo.lock, Cargo.toml, crates/action/src/attribute_manager/runner.rs, crates/common/Cargo.toml, crates/common/src/lib.rs, crates/common/src/serde.rs, crates/workflow/Cargo.toml, crates/workflow/src/workflow.rs
- add serde module and reearth-flow-common dependency
^ add serde module 
- add reearth-flow-common dependency
=> feat: add serde module and reearth-flow-common dependency

crates/action/src/action.rs, crates/action/src/attribute_merger.rs, crates/action/src/entity_transformer.rs, crates/action/src/file_reader/csv.rs, crates/action/src/file_reader/runner.rs, crates/action/src/file_writer.rs, crates/action/src/lib.rs
- add entity_transformer module and support for TSV format in file_reader and file_writer
- add entity_transformer module 
- support for TSV format in file_reader and file_writer
=> feat: add entity_transformer module and support for TSV format in file_reader and file_writer

crates/action/src/action.rs, crates/action/src/dataframe_transformer.rs, crates/action/src/lib.rs
- add dataframeTransformer action implementation
- dataframeTransformer action implementation
=> feat: add dataframeTransformer action implementation

Cargo.lock, Cargo.toml, crates/action/src/action.rs, crates/cli/Cargo.toml, crates/cli/src/run.rs, crates/common/src/str.rs, crates/state/src/lib.rs, crates/workflow-runner/Cargo.toml, crates/workflow-runner/src/dag/execution_dag.rs
- add reearth-flow-state crate and dependencies
=> feat add reearth-flow-state crate and dependencies

crates/workflow-runner/src/dag/execution_dag.rs
- refactor save method to convert ActionDataframe to HashMap
- refactor save method to convert ActionDataframe to HashMap
=> chore: refactor save method to convert ActionDataframe to HashMap

Cargo.lock, Cargo.toml, crates/action-log/Cargo.toml, crates/action-log/src/action.rs, crates/action-log/src/factory.rs, crates/action-log/src/lib.rs, crates/action-log/src/split.rs, crates/action/src/action.rs, crates/cli/Cargo.toml, crates/cli/src/run.rs, crates/common/src/uri.rs, crates/storage/src/storage.rs, crates/workflow-runner/Cargo.toml, crates/workflow-runner/src/dag/execution_dag.rs
- add reearth-flow-action-log.workspace dependency
- add reearth-flow-action-log.workspace dependency
=> feat: add reearth-flow-action-log.workspace dependency

Cargo.lock, crates/action-log/Cargo.toml, crates/action-log/src/lib.rs, crates/action/src/action.rs, crates/workflow-runner/src/dag/execution_dag.rs
- add tracing dependency and update action logging
- add tracing dependency and update action logging
=> chore: add tracing dependency and update action logging

crates/action/src/attribute_keeper.rs
- refactor attribute_keeper to filter out unwanted attributes
=> chore: refactor attribute_keeper to filter out unwanted attributes

crates/action-log/src/lib.rs, crates/workflow-runner/src/dag/execution_dag.rs
- refactor action logging macros
- refactor action logging macros
=> chore: refactor action logging macros

.github/workflows/crates-ci.yml, .github/workflows/crates-deny.yml
- rename github actions workflow
- chore: rename CI workflows for crates and deny checks
- chore: update CI workflows for crates and deny
=> chore: rename github actions workflow

worker/crates/action/src/attribute_aggregator.rs, worker/crates/action/src/attribute_keeper.rs, worker/crates/action/src/attribute_manager/runner.rs, worker/crates/action/src/attribute_merger.rs, worker/crates/action/src/color_converter/runner.rs, worker/crates/action/src/dataframe_transformer.rs, worker/crates/action/src/entity_filter.rs, worker/crates/action/src/entity_transformer.rs, worker/crates/action/src/file_reader/runner.rs, worker/crates/action/src/file_writer.rs, worker/crates/action/src/lib.rs, worker/crates/action/src/macros.rs, worker/crates/action/src/zip_extractor.rs
- add property_schema macro to convert NodeProperty to PropertySchema
=> chore: add property_schema macro to convert NodeProperty to PropertySchema

worker/README.md
-  update libxml2 installation instructions
=> chore(worker): update libxml2 installation instructions

worker/crates/eval-expr/src/engine.rs, worker/crates/eval-expr/src/module.rs, worker/crates/eval-expr/src/module/console.rs
- add console module to engine
=> feat(worker): add console module to engine

worker/Cargo.lock, worker/Cargo.toml, worker/crates/action/Cargo.toml, worker/crates/action/src/action.rs, worker/crates/action/src/attribute_aggregator.rs, worker/crates/action/src/attribute_keeper.rs, worker/crates/action/src/attribute_manager.rs, worker/crates/action/src/attribute_manager/runner.rs, worker/crates/action/src/attribute_merger.rs, worker/crates/action/src/color_converter.rs, worker/crates/action/src/color_converter/hsl_to_rgba.rs, worker/crates/action/src/color_converter/runner.rs, worker/crates/action/src/dataframe_transformer.rs, worker/crates/action/src/entity_filter.rs, worker/crates/action/src/entity_transformer.rs, worker/crates/action/src/file_reader.rs, worker/crates/action/src/file_reader/runner.rs, worker/crates/action/src/file_writer.rs, worker/crates/action/src/xml_xpath_extractor.rs, worker/crates/action/src/zip_extractor.rs
=> chore(worker): refactor action runners

worker/Cargo.lock, worker/Cargo.toml, worker/crates/action/Cargo.toml, worker/crates/action/src/action.rs, worker/crates/action/src/attribute_aggregator.rs, worker/crates/action/src/attribute_keeper.rs, worker/crates/action/src/attribute_manager.rs, worker/crates/action/src/attribute_manager/runner.rs, worker/crates/action/src/attribute_merger.rs, worker/crates/action/src/color_converter.rs, worker/crates/action/src/color_converter/hsl_to_rgba.rs, worker/crates/action/src/color_converter/runner.rs, worker/crates/action/src/dataframe_transformer.rs, worker/crates/action/src/entity_filter.rs, worker/crates/action/src/entity_transformer.rs, worker/crates/action/src/file_reader.rs, worker/crates/action/src/file_reader/csv.rs, worker/crates/action/src/file_reader/runner.rs, worker/crates/action/src/file_writer.rs, worker/crates/action/src/lib.rs, worker/crates/action/src/prelude.rs, worker/crates/action/src/xml_xpath_extractor.rs, worker/crates/action/src/zip_extractor.rs, worker/crates/workflow-runner/src/action_runner.rs, worker/crates/workflow-runner/src/dag/dag_impl.rs, worker/crates/workflow-runner/src/dag/execution_dag.rs, worker/crates/workflow-runner/src/lib.rs
- refactor code structure and module imports
=> feat(worker): refactor code structure and module imports

worker/Cargo.lock, worker/crates/action-universal/Cargo.toml, worker/crates/action-universal/src/attribute_manager/runner.rs, worker/crates/action-universal/src/entity_filter.rs, worker/crates/action-universal/src/entity_transformer.rs, worker/crates/action/src/lib.rs, worker/crates/common/Cargo.toml, worker/crates/common/src/collection.rs, worker/crates/common/src/lib.rs
- update dependencies and add collection module
=> feat(worker): update dependencies and add collection module

worker/crates/action-log/src/lib.rs, worker/crates/action-universal/src/entity_filter.rs, worker/crates/workflow-runner/src/action_runner.rs
- add span function to action-log crate
=> chore: add span function to action-log crate

worker/crates/action-universal/src/attribute_aggregator.rs, worker/crates/action-universal/src/attribute_keeper.rs, worker/crates/action-universal/src/attribute_manager/runner.rs, worker/crates/action-universal/src/attribute_merger.rs, worker/crates/action-universal/src/color_converter/runner.rs, worker/crates/action-universal/src/dataframe_transformer.rs, worker/crates/action-universal/src/entity_filter.rs, worker/crates/action-universal/src/entity_transformer.rs, worker/crates/action-universal/src/file_reader/runner.rs, worker/crates/action-universal/src/file_writer.rs, worker/crates/action-universal/src/xml_xpath_extractor.rs, worker/crates/action-universal/src/zip_extractor.rs, worker/crates/workflow-runner/src/dag/execution_dag.rs
- update serde names in action-universal crate
=> chore(worker): update serde names in action-universal crate

worker/Cargo.lock, worker/crates/action-universal/Cargo.toml, worker/crates/action/Cargo.toml, worker/crates/workflow-runner/src/action_runner.rs, worker/crates/workflow-runner/src/dag/execution_dag.rs
- update dependencies and refactor ActionRunner
=> chore(worker): update dependencies and refactor ActionRunner

worker/crates/action-universal/src/lib.rs, worker/crates/action-universal/src/rhai_caller.rs, worker/crates/action/src/lib.rs
- add RhaiCaller module to action-universal crate
=> feat(worker): add RhaiCaller module to action-universal crate

worker/crates/cli/src/cli.rs, worker/crates/cli/src/dot.rs, worker/crates/cli/src/lib.rs, worker/crates/workflow-runner/src/dag/dag_impl.rs
=> feat: add dot command to CLI

worker/crates/action-universal/src/attribute_sorter.rs, worker/crates/workflow-runner/src/dag/dag_impl.rs, worker/crates/workflow/src/graph.rs
- add action method to Node struct and implement From trait for NodeType
=> chore: add action method to Node struct and implement From trait for NodeType

worker/Cargo.lock, worker/Cargo.toml, worker/crates/action-plateau/Cargo.toml, worker/crates/action-plateau/src/file_path_extractor.rs, worker/crates/action-plateau/src/lib.rs, worker/crates/action-plateau/src/prelude.rs, worker/crates/action-universal/Cargo.toml, worker/crates/action-universal/src/attribute_aggregator.rs, worker/crates/action-universal/src/dataframe_union.rs, worker/crates/action-universal/src/entity_filter.rs, worker/crates/action-universal/src/file_reader/runner.rs, worker/crates/action-universal/src/lib.rs, worker/crates/action-universal/src/prelude.rs, worker/crates/action-universal/src/rhai_caller.rs, worker/crates/action-universal/src/xml_xpath_extractor.rs, worker/crates/action-universal/src/zip_extractor.rs, worker/crates/action/src/lib.rs, worker/crates/action/src/utils.rs, worker/crates/action/src/utils/dir.rs, worker/crates/action/src/utils/zip.rs, worker/crates/common/Cargo.toml, worker/crates/common/src/lib.rs, worker/crates/common/src/uri.rs, worker/crates/workflow-runner/Cargo.toml, worker/crates/workflow-runner/src/action_runner.rs
- add new modules and dependencies
=> feat(worker): add new modules and dependencies

worker/Cargo.lock, worker/Cargo.toml, worker/crates/common/Cargo.toml, worker/crates/common/src/fs.rs, worker/crates/workflow-runner/Cargo.toml
- add async-recursion dependency
=> feat(worker): add async-recursion dependency

worker/crates/action-plateau/src/lib.rs, worker/crates/action-plateau/src/prelude.rs, worker/crates/action-plateau/src/udx_folder_extractor.rs, worker/crates/action-universal/src/file_path_extractor.rs, worker/crates/action-universal/src/lib.rs, worker/crates/action-universal/src/prelude.rs, worker/crates/common/src/uri.rs, worker/crates/storage/src/storage.rs
- refactor file path extraction and update dependencies
=> chore(worker): refactor file path extraction and update dependencies

worker/crates/action-universal/src/entity/transformer.rs
- refactor EntityTransformer to support multiple transforms
=> feat(worker): refactor EntityTransformer to support multiple transforms

worker/Cargo.lock, worker/crates/action-universal/Cargo.toml, worker/crates/action-universal/src/attribute/keeper.rs, worker/crates/action-universal/src/attribute/sorter.rs, worker/crates/action-universal/src/entity/transformer.rs, worker/crates/action-universal/src/file/reader/runner.rs, worker/crates/action-universal/src/plateau.rs, worker/crates/action-universal/src/plateau/dictionaries_initiator.rs, worker/crates/action-universal/src/plateau/udx_folder_extractor.rs, worker/crates/common/src/uri.rs, worker/crates/common/src/xml.rs
- add once_cell crate and make some code improvements
=> WIP: feat(worker): add once_cell crate and make some code improvements

worker/Cargo.lock, worker/Cargo.toml, worker/crates/action-universal/Cargo.toml, worker/crates/action-universal/src/attribute/aggregator.rs, worker/crates/action-universal/src/attribute/merger.rs, worker/crates/action-universal/src/attribute/sorter.rs, worker/crates/action-universal/src/dataframe/transformer.rs, worker/crates/action-universal/src/entity/counter.rs, worker/crates/action-universal/src/entity/filter.rs, worker/crates/action-universal/src/entity/transformer.rs, worker/crates/action-universal/src/file/path_extractor.rs, worker/crates/action-universal/src/file/reader/runner.rs, worker/crates/action-universal/src/file/writer.rs, worker/crates/action-universal/src/plateau.rs, worker/crates/action-universal/src/plateau/dictionaries_initiator.rs, worker/crates/action-universal/src/plateau/types.rs, worker/crates/action-universal/src/plateau/udx_folder_extractor.rs, worker/crates/action-universal/src/plateau/xml_attribute_extractor.rs, worker/crates/action-universal/src/rhai_caller.rs, worker/crates/action-universal/src/zip_extractor.rs, worker/crates/action/Cargo.toml, worker/crates/action/src/lib.rs, worker/crates/action/src/utils.rs, worker/crates/common/src/uri.rs, worker/crates/common/src/xml.rs, worker/crates/workflow-runner/src/action_runner.rs, worker/crates/workflow-runner/src/dag/dag_impl.rs, worker/crates/workflow-runner/src/dag/execution_dag.rs
- Add regex dependency and new modules for plateau
=> feat(worker): Add regex dependency and new modules for plateau

worker/crates/action-universal/src/attribute.rs, worker/crates/action-universal/src/attribute/aggregator.rs, worker/crates/action-universal/src/attribute/manager.rs, worker/crates/action-universal/src/color_converter/hsl_to_rgba.rs, worker/crates/action-universal/src/dataframe.rs, worker/crates/action-universal/src/dataframe/transformer.rs, worker/crates/action-universal/src/dataframe/unions.rs, worker/crates/action-universal/src/entity.rs, worker/crates/action-universal/src/file.rs, worker/crates/action-universal/src/file/reader/csv.rs, worker/crates/action-universal/src/file/reader/runner.rs, worker/crates/action-universal/src/plateau/types.rs, worker/crates/workflow-runner/src/dag/dag_impl.rs
=> chore(worker): Update module visibility

worker/crates/action-universal/src/dataframe/transformer.rs
- refactor DataframeTransformer to support additional operations
=> chore(worker): refactor DataframeTransformer to support additional operations

worker/Cargo.lock, worker/Cargo.toml, worker/crates/action-universal/src/entity/transformer.rs, worker/crates/action-universal/src/prelude.rs, worker/crates/action-universal/src/xml.rs, worker/crates/action-universal/src/xml/fragmenter.rs, worker/crates/common/Cargo.toml, worker/crates/common/src/str.rs
- add sha2 crate and XmlFragmenter module
=> feat: add sha2 crate and XmlFragmenter module

worker/crates/storage/src/storage.rs, worker/examples/plateau/testdata/graphs/attribute_reader.yml, worker/examples/plateau/testdata/graphs/folder_and_file_path_reader.yml, worker/examples/plateau/testdata/workflow/folder_and_file_path_reader.yaml
- fix directory creation bug and update file paths
=> chore(worker): fix directory creation bug and update file paths

worker/Makefile.toml, worker/README.md
- add example task to Makefile.toml
=> chore(worker): add example task to Makefile.toml

worker/crates/action-universal/src/plateau/xml_attribute_extractor.rs, worker/crates/action/src/lib.rs, worker/examples/plateau/testdata/workflow/attribute_reader.yml
- update XMLAttributeExtractor serde name and cityGmlPath URL
=> chore(worker): update XMLAttributeExtractor serde name and cityGmlPath URL

worker/examples/plateau/runner.rs
=> chore(worker): update examples runner

worker/Cargo.lock, worker/crates/eval-expr/Cargo.toml, worker/crates/eval-expr/src/engine.rs, worker/crates/eval-expr/src/module.rs, worker/crates/eval-expr/src/module/file.rs, worker/crates/eval-expr/src/module/str.rs, worker/examples/plateau/runner.rs, worker/examples/plateau/testdata/graphs/attribute_reader.yml
- add file and str modules to eval-expr engine
=> feat(worker): add file and str modules to eval-expr engine

worker/Cargo.lock, worker/Cargo.toml, worker/crates/action-universal/src/xml/fragmenter.rs, worker/crates/action/src/lib.rs, worker/crates/cli/Cargo.toml, worker/examples/Cargo.toml, worker/examples/plateau/runner.rs, worker/examples/plateau/testdata/workflow/attribute_reader.yml
- update dependencies and setup logging and tracing
=> chore(worker): update dependencies and setup logging and tracing

worker/crates/action/src/lib.rs, worker/crates/action/src/value.rs, worker/examples/plateau/runner.rs
=> chore(worker): refactor action value

worker/Cargo.lock, worker/Cargo.toml, worker/crates/xml/Cargo.toml, worker/crates/xml/src/convert.rs, worker/crates/xml/src/decl.rs, worker/crates/xml/src/display.rs, worker/crates/xml/src/dom_impl.rs, worker/crates/xml/src/error.rs, worker/crates/xml/src/lib.rs, worker/crates/xml/src/mutex.rs, worker/crates/xml/src/name.rs, worker/crates/xml/src/namespace.rs, worker/crates/xml/src/node.rs, worker/crates/xml/src/options.rs, worker/crates/xml/src/parser.rs, worker/crates/xml/src/syntax.rs, worker/crates/xml/src/text.rs, worker/crates/xml/src/trait_impl.rs, worker/crates/xml/src/traits.rs
- add XML module and dependencies
=> feat(worker): add XML module and dependencies

worker/crates/xml/Cargo.toml, worker/crates/xml/src/error.rs, worker/crates/xml/src/parser.rs
- update XML crate dependencies and handle parsing errors
=> chore(worker): update XML crate dependencies and handle parsing errors

worker/Cargo.lock, worker/crates/action-universal/Cargo.toml, worker/crates/xml/src/display.rs, worker/crates/xml/src/lib.rs, worker/crates/xml/src/mutex.rs, worker/crates/xml/src/name.rs, worker/crates/xml/src/trait_impl.rs, worker/crates/xml/src/traits.rs
- add reearth-flow-xml crate and implement new methods in the Element trait
=> chore(worker): add reearth-flow-xml crate and implement new methods in the Element trait

worker/crates/action-universal/src/plateau/dictionaries_initiator.rs, worker/crates/action-universal/src/xml/fragmenter.rs, worker/crates/action/src/lib.rs, worker/crates/common/src/serde.rs, worker/crates/workflow-runner/src/action_runner.rs, worker/crates/workflow-runner/src/dag/execution_dag.rs, worker/crates/workflow/src/workflow.rs, worker/crates/xml/src/convert.rs, worker/crates/xml/src/decl.rs, worker/crates/xml/src/lib.rs, worker/crates/xml/src/namespace.rs, worker/crates/xml/src/node.rs, worker/crates/xml/src/parser.rs, worker/crates/xml/src/trait_impl.rs, worker/crates/xml/src/traits.rs, worker/examples/plateau/testdata/graphs/attribute_reader.yml, worker/examples/plateau/testdata/workflow/attribute_reader.yml
- fix XML parsing and fragmenting issues
=> feat(worker): fix XML parsing and fragmenting issues

worker/Cargo.lock, worker/crates/action-universal/src/xml/fragmenter.rs, worker/crates/common/src/collection.rs, worker/crates/storage/src/storage.rs, worker/crates/xml/Cargo.toml, worker/crates/xml/src/display.rs, worker/crates/xml/src/node.rs, worker/crates/xml/src/trait_impl.rs, worker/crates/xml/src/traits.rs, worker/examples/plateau/testdata/graphs/attribute_reader.yml
- add uuid crate and implement par_map function
=> feat(worker): add uuid crate and implement par_map function

worker/crates/action-universal/src/attribute/aggregator.rs, worker/crates/action-universal/src/attribute/keeper.rs, worker/crates/action-universal/src/attribute/manager.rs, worker/crates/action-universal/src/attribute/merger.rs, worker/crates/action-universal/src/attribute/searcher.rs, worker/crates/action-universal/src/attribute/sorter.rs, worker/crates/action-universal/src/color_converter/runner.rs, worker/crates/action-universal/src/dataframe/transformer.rs, worker/crates/action-universal/src/dataframe/unions.rs, worker/crates/action-universal/src/entity/counter.rs, worker/crates/action-universal/src/entity/filter.rs, worker/crates/action-universal/src/entity/transformer.rs, worker/crates/action-universal/src/file/path_extractor.rs, worker/crates/action-universal/src/file/reader/runner.rs, worker/crates/action-universal/src/file/writer.rs, worker/crates/action-universal/src/plateau/dictionaries_initiator.rs, worker/crates/action-universal/src/plateau/udx_folder_extractor.rs, worker/crates/action-universal/src/plateau/xml_attribute_extractor.rs, worker/crates/action-universal/src/rhai_caller.rs, worker/crates/action-universal/src/xml/fragmenter.rs, worker/crates/action-universal/src/xml/xpath_extractor.rs, worker/crates/action-universal/src/zip_extractor.rs, worker/crates/action/src/lib.rs, worker/crates/common/src/xml.rs, worker/crates/workflow-runner/src/action_runner.rs
- async trait naming in action module
=> feat(worker): async trait naming in action module

worker/crates/action-universal/src/xml/fragmenter.rs, worker/crates/common/src/xml.rs
- fix XML parsing and fragmenting issues in worker module
=> chore(worker): fix XML parsing and fragmenting issues in worker module

worker/crates/storage/src/lib.rs, worker/crates/storage/src/storage.rs, worker/crates/storage/src/storage_sync.rs
- add storage_sync module to storage crate
=> chore(worker): add storage_sync module to storage crate

worker/Cargo.lock, worker/crates/workflow-runner/Cargo.toml, worker/crates/workflow-runner/src/action_runner.rs
- Add once_cell and regex dependencies to worker crate
=> chore(worker): Add once_cell and regex dependencies to worker crate

worker/Cargo.lock, worker/crates/geometry/Cargo.toml, worker/crates/geometry/src/error.rs, worker/crates/geometry/src/lib.rs, worker/crates/geometry/src/macros.rs, worker/crates/geometry/src/types.rs, worker/crates/geometry/src/types/coordinate.rs, worker/crates/geometry/src/types/coordnum.rs, worker/crates/geometry/src/types/geometry.rs, worker/crates/geometry/src/types/geometry_collection.rs, worker/crates/geometry/src/types/line.rs, worker/crates/geometry/src/types/line_string.rs, worker/crates/geometry/src/types/multi_line_string.rs, worker/crates/geometry/src/types/multi_point.rs, worker/crates/geometry/src/types/multi_polygon.rs, worker/crates/geometry/src/types/no_value.rs, worker/crates/geometry/src/types/point.rs, worker/crates/geometry/src/types/polygon.rs, worker/crates/geometry/src/types/rect.rs, worker/crates/geometry/src/types/triangle.rs, worker/crates/geometry/src/utils.rs, worker/crates/geometry/src/wkt_macro.rs
- add geometry crate 
- unit testing
=> feat(worker): add geometry crate

worker/Cargo.lock, worker/crates/geometry/Cargo.toml, worker/crates/geometry/src/types.rs, worker/crates/geometry/src/types/geometry_2d.rs, worker/crates/geometry/src/types/geometry_3d.rs, worker/crates/geometry/src/types/line_string.rs, worker/crates/geometry/src/types/multi_line_string.rs, worker/crates/geometry/src/types/multi_point.rs, worker/crates/geometry/src/types/multi_polygon.rs, worker/crates/geometry/src/types/polygon.rs, worker/deny.toml
- add geometry_2d and geometry_3d modules to the geometry crate
=> feat(worker): add geometry_2d and geometry_3d modules to the geometry crate

worker/crates/xml/src/display.rs, worker/crates/xml/src/parser.rs, worker/crates/xml/src/trait_impl.rs, worker/crates/xml/src/traits.rs
- refactor XML formatting functions in worker crate
=> chore(worker): refactor XML formatting functions in worker crate

worker/Cargo.lock, worker/Cargo.toml
- update dependencies in worker crate
=> chore(worker): update dependencies in worker crate

worker/crates/action-universal/src/plateau/dictionaries_initiator.rs, worker/examples/plateau/runner.rs
- refactor dictionaries_initiator.rs and runner.rs files
=> chore(worker): refactor dictionaries_initiator.rs and runner.rs files

worker/crates/action-universal/src/xml/fragmenter.rs, worker/examples/plateau/runner.rs
- refactor XML fragmenter to improve performance and reduce duplicate XML generation
=> chore(worker): refactor XML fragmenter to improve performance and reduce duplicate XML generation

worker/crates/action-universal/src/xml.rs, worker/crates/action-universal/src/xml/formatter.rs
XMLFormatter
- Core functionally
- Tests
- Integrated tests
- Unit test
NA
NA
NA
=> feat(worker): format XML

worker/crates/action-universal/src/entity/filter.rs, worker/crates/action-universal/src/file/path_extractor.rs, worker/crates/action-universal/src/file/reader/citygml.rs, worker/crates/action-universal/src/file/reader/runner.rs, worker/crates/action-universal/src/plateau/xml_attribute_extractor.rs, worker/crates/action-universal/src/xml/formatter.rs, worker/crates/action-universal/src/xml/fragmenter.rs, worker/crates/action/src/lib.rs, worker/crates/action/src/utils.rs, worker/crates/workflow-runner/src/action_runner.rs
=> chore(worker): refactor action context

worker/Cargo.lock, worker/Cargo.toml, worker/crates/action-universal/src/file/reader/citygml.rs, worker/crates/action/Cargo.toml, worker/crates/action/src/types.rs, worker/crates/action/src/types/geometry.rs, worker/crates/action/src/value.rs, worker/crates/geometry/Cargo.toml, worker/crates/geometry/src/types.rs, worker/crates/geometry/src/types/geometry.rs, worker/crates/geometry/src/types/geometry_2d.rs, worker/crates/geometry/src/types/geometry_3d.rs, worker/crates/geometry/src/types/polygon.rs, worker/crates/geometry/src/types/rectangle.rs, worker/crates/geometry/src/types/traits.rs, worker/crates/geometry/src/types/triangle.rs, worker/crates/geometry/src/utils.rs, worker/tests/fixture/testdata/file/reader/citygml/udx/urf/533834_urf_6668_sigaidev_op.gml
- Refactor geometry crate and update dependencies
=> chore(worker): Refactor geometry crate and update dependencies

worker/crates/action-universal/src/feature/transformer.rs, worker/crates/action-universal/src/plateau/udx_folder_extractor.rs, worker/crates/action/src/dataframe.rs, worker/examples/plateau/runner.rs, worker/examples/plateau/testdata/workflow/attribute_reader.yml
- Refactor file paths and module names for entity-related code to feature-related code in worker crate
=> chore(worker): Refactor file paths and module names for entity-related code to feature-related code in worker crate

worker/Cargo.lock, worker/crates/cli/src/logger.rs, worker/examples/Cargo.toml, worker/examples/plateau/attribute_reader.rs, worker/examples/plateau/helper.rs
=> chore(worker): Add uuid crate as a dependency in Cargo.lock, logger.rs, and Cargo.toml

worker/crates/action-universal/src/attribute.rs, worker/crates/action-universal/src/attribute/length_calculator.rs
AttributeLengthCalculator for PLATEAU.MaxLODExtractor
=> feat(worker): add AttributeLengthCalculator

worker/crates/action/src/feature.rs
- Refactor Feature struct in feature.rs to remove _id field and simplify attribute conversion logic
=> chore(worker): Refactor Feature struct in feature.rs to remove _id field and simplify attribute conversion logic

worker/crates/action-universal/src/plateau.rs, worker/crates/action-universal/src/plateau/domain_of_definition_validator.rs, worker/crates/action-universal/src/plateau/xml_attribute_extractor.rs, worker/crates/action-universal/src/xml/fragmenter.rs, worker/crates/action/src/feature.rs, worker/crates/common/src/xml.rs
- add domain of definition validator action
=> feat(worker): add domain of definition validator action

worker/crates/action-universal/src/geometry/three_dimention_box_replacer.rs, worker/crates/geometry/src/types.rs, worker/crates/geometry/src/types/face.rs, worker/crates/geometry/src/types/line.rs, worker/crates/geometry/src/types/line_string.rs, worker/crates/geometry/src/types/polygon.rs, worker/crates/geometry/src/types/rectangle.rs, worker/crates/geometry/src/types/solid.rs
- refactor ThreeDimentionBoxReplacer to use iterator and improve error handling
=> feat(worker): refactor ThreeDimentionBoxReplacer to use iterator and improve error handling

worker/crates/action-universal/src/geometry.rs, worker/crates/action-universal/src/geometry/extruder.rs, worker/crates/action-universal/src/geometry/three_dimention_box_replacer.rs, worker/crates/geometry/src/types/geometry.rs
- refactor geometry module and add Extruder action
=> feat(worker): refactor geometry module and add Extruder action

worker/Cargo.lock, worker/crates/action-universal/Cargo.toml, worker/crates/action-universal/src/geometry.rs, worker/crates/action-universal/src/geometry/coordinate_system_setter.rs
- add coordinate system setter module
=> feat(worker): add coordinate system setter module

ui/package.json, ui/src/components/buttons/BaseButton/index.tsx, ui/src/config/index.ts, ui/src/features/Canvas/components/Breadcrumb/index.tsx, ui/src/features/Canvas/components/Infobar/index.tsx, ui/src/features/Canvas/components/index.ts, ui/src/features/Canvas/index.tsx, ui/src/features/Dashboard/components/LeftSection/components/WorkspaceMembers.tsx, ui/src/features/Dashboard/components/LeftSection/components/WorkspaceNavigation.tsx, ui/src/features/Dashboard/components/LeftSection/index.tsx, ui/src/features/Dashboard/components/MainSection.tsx, ui/src/features/Root/index.tsx, ui/src/mock_data/projectData.ts, ui/src/routes/__root.tsx, ui/src/routes/workspace_.$workspaceId_.project.$projectId.lazy.tsx, ui/src/types/project.ts
=> feat(ui): update dashboard and editor ui

worker/Cargo.lock, worker/crates/runtime/src/builder_dag.rs, worker/crates/runtime/src/dag_schemas.rs, worker/crates/runtime/src/node.rs, worker/examples/Cargo.toml, worker/examples/plateau/domain_of_definition_validator.rs, worker/examples/plateau/testdata/graphs/attribute_reader.yml, worker/examples/plateau/testdata/graphs/domain_of_definition_validator.yml, worker/examples/plateau/testdata/graphs/folder_and_file_path_reader.yml, worker/examples/plateau/testdata/graphs/xml_validator.yml, worker/examples/plateau/testdata/workflow/attribute_reader.yml
- add reearth-flow-runtime dependency and Router struct
=> feat: add reearth-flow-runtime dependency and Router struct

api/.env.example
This PR fixes `.env.example` of `api`
=> chore(api): fix env example

worker/Cargo.lock, worker/crates/action-processor/src/feature/transformer.rs, worker/crates/action-processor/src/plateau/domain_of_definition_validator.rs, worker/crates/action-processor/src/plateau/xml_attribute_extractor.rs, worker/crates/common/src/future.rs, worker/crates/common/src/lib.rs, worker/crates/common/src/xml.rs, worker/crates/runner/src/executor.rs, worker/crates/runner/src/orchestrator.rs, worker/crates/runner/src/runner.rs, worker/crates/runtime/Cargo.toml, worker/crates/runtime/src/dag_schemas.rs, worker/crates/runtime/src/executor/dag_executor.rs, worker/crates/runtime/src/executor/processor_node.rs, worker/crates/runtime/src/executor_operation.rs, worker/crates/runtime/src/node.rs, worker/examples/plateau/domain_of_definition_validator.rs, worker/examples/plateau/helper.rs, worker/examples/plateau/testdata/graphs/domain_of_definition_validator.yml, worker/examples/plateau/testdata/workflow/domain_of_definition_validator.yml, worker/examples/plateau/xml_validator.rs
-  update thread pool size for processors
=> feat(worker): update thread pool size for processors

schema/actions.json, worker/crates/action-processor/src/geometry/three_dimention_box_replacer.rs, worker/crates/cli/src/schema.rs, worker/crates/runner/src/runner.rs, worker/crates/runtime/src/builder_dag.rs, worker/crates/runtime/src/errors.rs
- Fix action name mismatch in BuilderDag
=> chore(worker): Fix action name mismatch in BuilderDag

schema/actions.json, worker/crates/cli/src/schema.rs
-  sort actions alphabetically in SchemaCliCommand
=> chore(worker): sort actions alphabetically in SchemaCliCommand

worker/crates/action-processor/src/xml/fragmenter.rs, worker/crates/runtime/src/executor/dag_executor.rs, worker/crates/runtime/src/executor/sink_node.rs
- Update SinkNode constructor to include shutdown and runtime parameters
=> chore(worker): Update SinkNode constructor to include shutdown and runtime parameters

schema/actions.json, worker/Cargo.lock, worker/Cargo.toml, worker/Makefile.toml, worker/README.md, worker/crates/action-processor/Cargo.toml, worker/crates/action-processor/src/attribute.rs, worker/crates/action-processor/src/attribute/errors.rs, worker/crates/action-processor/src/attribute/file_path_info_extractor.rs, worker/crates/action-processor/src/attribute/mapping.rs, worker/crates/action-processor/src/feature.rs, worker/crates/action-processor/src/feature/mapping.rs, worker/crates/action-processor/src/geometry.rs, worker/crates/action-processor/src/geometry/mapping.rs, worker/crates/action-processor/src/mapping.rs, worker/crates/action-processor/src/plateau.rs, worker/crates/action-processor/src/plateau/mapping.rs, worker/crates/action-processor/src/xml.rs, worker/crates/action-processor/src/xml/mapping.rs, worker/crates/common/src/fs.rs, worker/crates/runner/src/orchestrator.rs, worker/crates/runtime/Cargo.toml, worker/crates/storage/Cargo.toml, worker/crates/types/Cargo.toml, worker/crates/types/src/attribute.rs, worker/crates/types/src/datetime.rs, worker/crates/types/src/feature.rs, worker/crates/types/src/lib.rs
- add file info extractor action
=> feat(worker): add file info extractor action

worker/crates/action-processor/src/attribute/aggregator.rs, worker/crates/action-processor/src/attribute/duplicate_filter.rs, worker/crates/action-processor/src/attribute/file_path_info_extractor.rs, worker/crates/action-processor/src/attribute/keeper.rs, worker/crates/action-processor/src/attribute/manager.rs, worker/crates/action-processor/src/feature/counter.rs, worker/crates/action-processor/src/feature/filter.rs, worker/crates/action-processor/src/feature/merger.rs, worker/crates/action-processor/src/feature/sorter.rs, worker/crates/action-processor/src/feature/transformer.rs, worker/crates/action-processor/src/geometry/coordinate_system_setter.rs, worker/crates/action-processor/src/geometry/extruder.rs, worker/crates/action-processor/src/geometry/three_dimention_box_replacer.rs, worker/crates/action-processor/src/plateau/dictionaries_initiator.rs, worker/crates/action-processor/src/plateau/domain_of_definition_validator.rs, worker/crates/action-processor/src/plateau/udx_folder_extractor.rs, worker/crates/action-processor/src/plateau/xml_attribute_extractor.rs, worker/crates/action-processor/src/xml/validator.rs, worker/crates/common/src/collection.rs, worker/crates/common/src/xml.rs, worker/crates/geometry/src/types/geometry.rs, worker/crates/runtime/src/node.rs, worker/crates/types/src/geometry.rs, worker/examples/plateau/helper.rs, worker/examples/plateau/testdata/workflow/attribute_reader.yml, worker/examples/plateau/testdata/workflow/xml_validator.yml
-  Update XML validator workflow to use new XML file
- feat: Update XML validator workflow to use new XML file**
- feat(worker): Update num_threads in processors to improve performance**
=> feat(worker):  Update XML validator workflow to use new XML file

worker/crates/action-processor/src/xml/validator.rs, worker/crates/cli/src/run.rs, worker/crates/common/src/dir.rs, worker/crates/common/src/xml.rs, worker/crates/runtime/src/forwarder.rs, worker/examples/plateau/helper.rs
- Update cache directory path in code files
=> chore(worker): Update cache directory path in code files

worker/crates/runtime/src/feature_store.rs
- Refactor FeatureWriter flush method to convert features into serde_json::Value
=> chore(worker): Refactor FeatureWriter flush method to convert features into serde_json::Value

worker/crates/runner/src/runner.rs, worker/crates/runtime/src/executor/processor_node.rs, worker/crates/runtime/src/executor/source_node.rs
- Add tracing to workflow runner
=> feat(worker): Add tracing to workflow runner

worker/Cargo.lock, worker/crates/action-log/Cargo.toml, worker/crates/action-log/src/action.rs, worker/crates/action-log/src/lib.rs, worker/crates/action-processor/src/feature/filter.rs, worker/crates/action-processor/src/geometry.rs, worker/crates/action-processor/src/geometry/errors.rs, worker/crates/action-processor/src/geometry/filter.rs, worker/crates/action-processor/src/geometry/mapping.rs, worker/crates/geometry/src/types.rs, worker/crates/geometry/src/types/geometry.rs, worker/crates/geometry/src/types/geometry_collection.rs, worker/crates/runtime/src/executor/processor_node.rs, worker/crates/storage/src/storage.rs, worker/crates/storage/src/storage_sync.rs, worker/examples/plateau/attribute_reader.rs, worker/examples/plateau/testdata/workflow/lod_splitter_with_dm.yml, worker/examples/plateau/xml_validator.rs
- add geometry_collection module to the geometry crate
- add geometry_collection module to the geometry crate
- N/A
- N/A
- N/A
- N/A
- N/A
=> feat(worker): add geometry_collection module to the geometry crate

schema/actions.json, worker/Cargo.lock, worker/crates/action-processor/src/feature/reader/citygml.rs, worker/crates/action-processor/src/geometry.rs, worker/crates/action-processor/src/geometry/filter.rs, worker/crates/action-processor/src/geometry/mapping.rs, worker/crates/action-processor/src/geometry/splitter.rs, worker/crates/action-source/src/file/reader/citygml.rs, worker/crates/types/src/feature.rs, worker/crates/types/src/geometry.rs, worker/examples/plateau/testdata/workflow/lod_splitter_with_dm.yml
- add splitter module to the geometry crate
=> feat(worker): add splitter module to the geometry crate

worker/crates/cli/src/dot.rs
=> chore(worker): modify dot command

worker/crates/geometry/src/algorithm.rs, worker/crates/geometry/src/algorithm/contains.rs, worker/crates/geometry/src/algorithm/contains/line.rs, worker/crates/geometry/src/algorithm/contains/line_string.rs, worker/crates/geometry/src/algorithm/contains/point.rs, worker/crates/geometry/src/algorithm/contains/polygon.rs, worker/crates/geometry/src/algorithm/contains/rect.rs, worker/crates/geometry/src/algorithm/contains/triangle.rs, worker/crates/geometry/src/algorithm/dimensions.rs, worker/crates/geometry/src/algorithm/line_intersection.rs, worker/crates/geometry/src/types/polygon.rs, worker/crates/geometry/src/utils.rs
- add contains module to algorithm crate
=> feat(worker): add contains module to algorithm crate

schema/actions.json, worker/crates/action-processor/src/geometry.rs, worker/crates/action-processor/src/geometry/errors.rs, worker/crates/action-processor/src/geometry/mapping.rs, worker/crates/action-processor/src/geometry/two_dimention_forcer.rs, worker/crates/geometry/src/types/coordinate.rs, worker/crates/geometry/src/types/line_string.rs, worker/crates/geometry/src/types/multi_polygon.rs, worker/crates/geometry/src/types/polygon.rs, worker/crates/types/src/geometry.rs
- Add two_dimention_forcer module to geometry module
=> feat(worker): Add two_dimention_forcer module to geometry module

schema/actions.json, worker/crates/action-processor/src/geometry.rs, worker/crates/action-processor/src/geometry/errors.rs, worker/crates/action-processor/src/geometry/extractor.rs, worker/crates/action-processor/src/geometry/mapping.rs, worker/crates/action-processor/src/geometry/three_dimention_box_replacer.rs, worker/crates/action-processor/src/geometry/two_dimention_forcer.rs
- add geometry extractor module
=> feat(worker): add geometry extractor module

worker/Cargo.lock, worker/crates/geometry/Cargo.toml, worker/crates/geometry/src/algorithm.rs, worker/crates/geometry/src/algorithm/relate/edge_end_builder.rs, worker/crates/geometry/src/algorithm/relate/geomgraph/geometry_graph.rs, worker/crates/geometry/src/algorithm/relate/geomgraph/index/edge_set_intersector.rs, worker/crates/geometry/src/algorithm/relate/geomgraph/index/rstar_edge_set_intersector.rs, worker/crates/geometry/src/algorithm/relate/geomgraph/index/segment_intersector.rs, worker/crates/geometry/src/algorithm/relate/geomgraph/index/simple_edge_set_intersector.rs, worker/crates/geometry/src/algorithm/relate/geomgraph/planar_graph.rs, worker/crates/geometry/src/algorithm/relate/relate_operation.rs, worker/crates/geometry/src/algorithm/sweep.rs, worker/crates/geometry/src/algorithm/sweep/active.rs, worker/crates/geometry/src/algorithm/sweep/cross.rs, worker/crates/geometry/src/algorithm/sweep/events.rs, worker/crates/geometry/src/algorithm/sweep/im_segment.rs, worker/crates/geometry/src/algorithm/sweep/iter.rs, worker/crates/geometry/src/algorithm/sweep/line_or_point.rs, worker/crates/geometry/src/algorithm/sweep/point.rs, worker/crates/geometry/src/algorithm/sweep/proc.rs, worker/crates/geometry/src/algorithm/sweep/segment.rs, worker/crates/geometry/src/algorithm/sweep/vec_set.rs
- Add parking_lot crate to dependencies and implement sweep algorithm module
=> feat(worker): Add parking_lot crate to dependencies and implement sweep algorithm module

worker/README.md, worker/crates/cli/src/dot.rs, worker/crates/cli/src/run.rs, worker/crates/types/src/workflow.rs, worker/examples/plateau/testdata/workflow/lod_splitter_with_dm.yml
- Add environment variable for cityGmlPath in worker
=> feat(worker): Add environment variable for cityGmlPath in worker

worker/Makefile.toml, worker/README.md, worker/examples/plateau/testdata/workflow/attribute_reader.yml, worker/examples/plateau/testdata/workflow/domain_of_definition_validator.yml, worker/examples/plateau/testdata/workflow/lod_splitter_with_dm.yml, worker/examples/plateau/testdata/workflow/xml_validator.yml
- Update Makefile.toml and README.md for cityGmlPath environment variable
=> chore(worker): Update Makefile.toml and README.md for cityGmlPath environment variable

schema/actions.json, worker/README.md, worker/crates/action-processor/src/geometry.rs, worker/crates/action-processor/src/geometry/errors.rs, worker/crates/action-processor/src/geometry/mapping.rs, worker/crates/action-processor/src/geometry/orientation_extractor.rs, worker/crates/geometry/src/algorithm/winding_order.rs
- Add orientation_extractor module to geometry
=> feat(worker): Add orientation_extractor module to geometry

worker/Cargo.lock, worker/Cargo.toml, worker/crates/action-processor/src/geometry.rs, worker/crates/action-processor/src/geometry/errors.rs, worker/crates/action-processor/src/geometry/mapping.rs, worker/crates/action-processor/src/geometry/validator.rs, worker/crates/common/Cargo.toml, worker/crates/common/src/collection.rs, worker/crates/geometry/Cargo.toml, worker/crates/geometry/src/lib.rs, worker/crates/geometry/src/types/coordinate.rs, worker/crates/geometry/src/types/line.rs, worker/crates/geometry/src/types/line_string.rs, worker/crates/geometry/src/types/multi_line_string.rs, worker/crates/geometry/src/types/multi_point.rs, worker/crates/geometry/src/types/multi_polygon.rs, worker/crates/geometry/src/types/no_value.rs, worker/crates/geometry/src/types/point.rs, worker/crates/geometry/src/types/polygon.rs, worker/crates/geometry/src/types/rect.rs, worker/crates/geometry/src/types/solid.rs, worker/crates/geometry/src/types/triangle.rs, worker/crates/geometry/src/validation.rs
- add approx crate to dependencies for geometry and action-processor modules
=> feat(worker): add approx crate to dependencies for geometry and action-processor modules

worker/crates/action-processor/src/geometry/validator.rs, worker/crates/geometry/src/algorithm/contains/point.rs, worker/crates/geometry/src/utils.rs, worker/crates/geometry/src/validation.rs
The commit adds a new function `check_coord_is_not_finite` to the
`utils.rs` file in the `geometry` module. This function checks if the
coordinates of a given geometry are finite and returns a boolean value
accordingly.
=> feat(geometry): add check_coord_is_not_finite function

worker/crates/geometry/src/algorithm.rs, worker/crates/geometry/src/algorithm/area2d.rs, worker/crates/geometry/src/algorithm/area3d.rs, worker/crates/geometry/src/algorithm/map_coords.rs, worker/crates/geometry/src/algorithm/remove_repeated_points.rs, worker/crates/geometry/src/types/coordinate.rs, worker/crates/geometry/src/types/coordnum.rs, worker/crates/geometry/src/types/line.rs, worker/crates/geometry/src/types/no_value.rs, worker/crates/geometry/src/utils.rs
=> feat(worker): add Default trait to Coordinate<T, Z>

websocket/crates/infra/src/persistence/project_repository.rs
=> docs(websocket): remove unnecessary comments

worker/Cargo.lock, worker/Cargo.toml, worker/crates/cli/Cargo.toml, worker/crates/macros/Cargo.toml, worker/crates/storage/Cargo.toml
- bump up opendal, serde_with, clap, proc-macro2, and reqwest dependencies
=> chore(worker): bump up opendal, serde_with, clap, proc-macro2, and reqwest dependencies

ui/src/components/ActionItem/index.tsx, ui/src/features/Editor/components/LeftPanel/components/Actions/Action.tsx, ui/src/features/Editor/components/LeftPanel/components/Actions/index.tsx
=> fix(ui): action dnd from actions list in left panel

worker/crates/runtime/src/builder_dag.rs, worker/crates/runtime/src/dag_schemas.rs, worker/crates/runtime/src/executor/execution_dag.rs, worker/crates/runtime/src/node.rs, worker/examples/plateau/example_feature_transformer.rs
=> feat(worker): update edge id for worker runtime

.github/actions/build_deploy_api/action.yml, .github/actions/build_deploy_ui/action.yml, .github/workflows/deploy_api_nightly.yml, .github/workflows/deploy_ui_nightly.yml
=> ci(ui, api): add nightly deploy actions

.github/workflows/pr.yml
=> ci: add assign author job on pr actions

.github/workflows/release_quality_checker.yaml
=> ci: update working directory paths for plateau-gis-quality-checker

.github/workflows/release_quality_checker.yaml
=> chore(engine): remove macOS target from release quality checker workflow

api/e2e/gql_deployment_test.go, api/gql/deployment.graphql, api/gql/project.graphql, api/internal/adapter/gql/generated.go, api/internal/adapter/gql/gqlmodel/models_gen.go, api/internal/adapter/gql/resolver_mutation_deployment.go, api/internal/adapter/gql/resolver_mutation_project.go, api/internal/usecase/interactor/deployment.go, api/internal/usecase/interactor/project.go, api/internal/usecase/interfaces/deployment.go, api/internal/usecase/interfaces/project.go
=> refactor(api): modify deployments to accept a yaml file, not zip

ui/docker/reearth_config.json.template
=> fix(ui): remove trailing comma from reearth config

engine/README.md
=> chore(engine): add runtime environment variables section to README

ui/src/features/Editor/components/Canvas/useBatch.ts, ui/src/features/Editor/components/Canvas/useDnd.ts, ui/src/features/Editor/components/Canvas/useNodes.ts, ui/src/features/Editor/components/OverlayUI/components/NodePickerDialog/index.tsx
=> fix(ui): dropping into batch nodes

api/internal/adapter/gql/gqlmodel/convert_deployment.go, api/internal/app/repo.go, api/internal/infrastructure/fs/file.go, api/internal/infrastructure/gcpbatch/batch.go, api/internal/infrastructure/gcpbatch/batch_test.go, api/internal/infrastructure/gcs/file.go, api/internal/infrastructure/mongo/mongodoc/deployment.go, api/internal/infrastructure/mongo/mongodoc/job.go, api/internal/usecase/gateway/batch.go, api/internal/usecase/gateway/file.go, api/internal/usecase/interactor/deployment.go, api/internal/usecase/interactor/project.go, api/pkg/deployment/builder.go, api/pkg/deployment/deployment.go, api/pkg/job/builder.go, api/pkg/job/job.go, api/pkg/workflow/metadata.go
=> refactor(api): move metadata with modularity

ui/src/utils/yamlToFormData.test.ts, ui/src/utils/yamlToFormData.ts
=> fix(ui): yaml->yml

api/internal/app/file.go, api/internal/infrastructure/fs/file.go, api/internal/infrastructure/gcs/file.go, api/internal/usecase/gateway/file.go
=> chore(api): support HEAD method for served File and metadata endpoint

engine/Cargo.lock
=> chore(engine): bump external crates

api/internal/infrastructure/gcpbatch/batch.go, api/internal/usecase/interactor/job.go
=> chore(api): debug statement for batch related functions

.github/workflows/build_deploy_websocket.yml, server/api/Dockerfile
=> chore(ci): remove GCS storage feature flag from build configuration

server/api/internal/infrastructure/gcpbatch/batch.go
=> chore(api): lint on batch config

server/websocket/Dockerfile.websocket
=> chore(websocket): build with no default features in Dockerfile

server/api/Dockerfile
=> chore(api): remove ffi at docker

server/api/internal/usecase/interactor/job.go
=> chore(api): refactor job completion method

.github/workflows/update_policies.yml, server/api/internal/rbac/definitions.go
=> fix: update policies workflow [FLOW-BE-52]

server/api/internal/infrastructure/gcpbatch/batch.go
=> chore(api): remove pubsub noop command from batch

go.work.sum, server/api/e2e/gql_workspace_test.go, server/api/go.mod, server/api/go.sum, server/api/internal/infrastructure/mongo/container.go, server/api/internal/usecase/repo/container.go
=> chore: fix-add-migration-to-AddUserMember-interactor [FLOW-BE-62]

.github/workflows/build_deploy_policies_cerbos.yml, .github/workflows/build_docker_push_worker.yml, .github/workflows/ci.yml, engine/Cargo.lock, engine/Cargo.toml, engine/plateau-gis-quality-checker/src-tauri/Cargo.toml
=> ci: refactor policy deployment action

server/subscriber/Dockerfile
=> chore(subscriber): update path in dockerfile and refactor [FLOW-BE-101]

engine/Cargo.lock, engine/Cargo.toml, engine/README.md, engine/plateau-gis-quality-checker/src-tauri/Cargo.toml, engine/runtime/common/Cargo.toml, engine/runtime/common/src/dir.rs
=> chore(engine): update package versions and add working directory configuration

.github/workflows/build_deploy_subscriber.yml, server/subscriber/Dockerfile
=> ci(subscriber): update deploy subscriber workflow and refactor dockerfile

server/Cargo.lock, server/websocket/Cargo.toml, server/websocket/src/broadcast/group.rs, server/websocket/src/broadcast/mod.rs, server/websocket/src/broadcast/pool.rs, server/websocket/src/broadcast/tasks.rs, server/websocket/src/broadcast/types.rs, server/websocket/src/server.rs, server/websocket/src/storage/redis/mod.rs
=> feat(websocket): enable brotli compression for HTTP responses  [FLOW-BE-120]

server/Cargo.lock, server/websocket/Cargo.toml, server/websocket/src/broadcast/group.rs, server/websocket/src/broadcast/mod.rs, server/websocket/src/broadcast/pool.rs, server/websocket/src/broadcast/tasks.rs, server/websocket/src/broadcast/types.rs, server/websocket/src/server.rs, server/websocket/src/storage/redis/mod.rs
…ness updater, Redis subscriber, and heartbeat tasks
=> refactor(ws): graceful shutdown [FLOW-BE-118]

server/websocket/src/storage/redis/mod.rs
…ethods for improved readability and consistency
=> refactor(redis): streamline Redis connection handling [FLOW-BE-107]

server/websocket/Cargo.lock, server/websocket/Cargo.toml, server/websocket/src/broadcast/group.rs, server/websocket/src/broadcast/pool.rs, server/websocket/src/ws.rs
=> refactor(group): enhance logging and manage active subscriptions in BroadcastGroup

server/websocket/src/broadcast/group.rs, server/websocket/src/broadcast/publish.rs, server/websocket/src/storage/redis/mod.rs, server/websocket/src/ws.rs
=> refactor(broadcast): enhance Publish and RedisStore for improved update handling with instance tracking

server/websocket/src/broadcast/group.rs, server/websocket/src/broadcast/pool.rs, server/websocket/src/broadcast/publish.rs, server/websocket/src/storage/redis/mod.rs
=> refactor(broadcast): streamline Redis update handling by removing origin tracking and enhancing read methods for improved performance

engine/README.md
Improves the explanation for the schema generation command
=> docs(engine): improve explanation for schema file generation command

engine/Cargo.lock, engine/Cargo.toml, engine/plateau-gis-quality-checker/src-tauri/Cargo.toml, engine/runtime/examples/example_main.rs, engine/worker/Cargo.toml, engine/worker/src/factory.rs
This pull request resolves the 'Action not found: WasmRuntimeExecutor' error occurring in the worker environment.
=> fix(engine): fix 'Action not found: WasmRuntimeExecutor' error for worker

server/websocket/src/broadcast/group.rs, server/websocket/src/broadcast/pool.rs, server/websocket/src/broadcast/publish.rs
=> refactor(websocket): replace flush mechanism with new data trigger for publishing updates [FLOW-BE-158]

go.work.sum, server/api/gql/document.graphql, server/api/internal/adapter/gql/generated.go, server/api/internal/adapter/gql/resolver_document.go, server/websocket/Cargo.lock, server/websocket/Cargo.toml, server/websocket/src/broadcast/pool.rs
=> fix(websocket): saveSnapshot mutation always returning true issue [FLOW-BE-159]

.github/workflows/license_check.yml
=> ci: remove license checker temporarily

server/websocket/src/broadcast/pool.rs
=> fix(websocket): revert flush_to_gcs

server/api/internal/app/graphql.go, server/api/internal/usecase/interactor/job.go, server/api/internal/usecase/interactor/log.go, server/api/internal/usecase/interactor/node.go, server/api/pkg/subscription/job_subscription.go, server/api/pkg/subscription/log_subscription.go, server/api/pkg/subscription/node_subscription.go
=> perf(api): optimize WebSocket performance and monitoring intervals [FLOW-BE-162]

server/websocket/src/broadcast/pool.rs
=> chore(websocket): optimize document load time

server/websocket/src/broadcast/group.rs, server/websocket/src/broadcast/pool.rs, server/websocket/src/doc/handler.rs, server/websocket/src/storage/kv/mod.rs, server/websocket/tests/ydoc.rs
…ions
Fix transaction deadlock issue in BroadcastGroup where duplicate transaction acquisition was causing the application to hang.
=> fix(websocket): prevent txn deadlock by removing duplicate transaction calls [FLOW-BE-165]

server/websocket/benches/server_bench.rs, server/websocket/src/broadcast/group.rs, server/websocket/src/broadcast/pool.rs, server/websocket/src/doc/handler.rs, server/websocket/src/server.rs, server/websocket/src/storage/redis/mod.rs, server/websocket/tests/flush_to_gcs_test.rs
=> refactor(websocket): simplify string formatting in various modules [FLOW-BE-169]

ui/CLAUDE.md
=> chore(ui): add CLAUDE.md file for better claude code support

server/api/internal/adapter/context.go, server/api/internal/adapter/gql/gqlmodel/convert_user.go, server/api/internal/app/auth_server.go
=> feat(api): enhance user metadata handling for language support

server/websocket/src/storage/redis/mod.rs, server/websocket/src/ws.rs
=> fix(websocket): fix Ping-Pong Busy Loop [FLOW-BE-170]

server/api/internal/infrastructure/gcpbatch/batch.go, server/api/internal/usecase/interactor/job.go
=> fix(api): enhance job status handling and monitoring logic[FLOW-BE-171]

engine/Cargo.lock, engine/Cargo.toml, engine/docs/mdbook/src/action.md, engine/plateau-gis-quality-checker/src-tauri/Cargo.toml, engine/runtime/action-plateau-processor/src/plateau3/building_usage_attribute_validator.rs, engine/runtime/action-plateau-processor/src/plateau3/xml_attribute_extractor.rs, engine/runtime/action-processor/src/geometry/bounds_extractor.rs, engine/schema/actions.json, engine/schema/actions_en.json, engine/schema/actions_es.json, engine/schema/actions_fr.json, engine/schema/actions_ja.json, engine/schema/actions_zh.json
While investigating actions and workflows I found some actions with defined parameters in a workflow that were not available in the schema.
Investigating futher found that three actions had parameters not being exposed in the schema
Updated the 3 actions to process the parameters instead of setting to "none" and regenerated the schema, verifying the parameters show now.
=> fix(engine): missing action parameters

ui/src/components/visualizations/MapLibre/index.tsx, ui/src/features/Editor/components/OverlayUI/components/DebugPanel/hooks.ts, ui/src/lib/i18n/locales/en.json, ui/src/lib/i18n/locales/es.json, ui/src/lib/i18n/locales/fr.json, ui/src/lib/i18n/locales/ja.json, ui/src/lib/i18n/locales/zh.json
Remove Map libre infobox and adjust map zoom
- No longer use an info box for the maplibre component
- Prevent map zooming in as much on double click
=> fix(refactor):  Remove infobox and adjust map zoom

engine/Cargo.lock, engine/Cargo.toml, engine/plateau-gis-quality-checker/src-tauri/Cargo.toml, engine/plateau-gis-quality-checker/src-tauri/src/main.rs, engine/runtime/sevenz/src/reader.rs
=> chore(engine): fix minor issues

engine/Cargo.lock, engine/Cargo.toml, engine/plateau-gis-quality-checker/src-tauri/Cargo.toml, engine/runtime/types/src/lod.rs
=> fix(engine): bugfix for remove_lod

engine/Cargo.lock, engine/Cargo.toml, engine/docs/mdbook/src/action.md, engine/plateau-gis-quality-checker/src-tauri/Cargo.toml, engine/runtime/action-wasm-processor/src/runtime_executor.rs, engine/runtime/examples/fixture/workflow/requirement/plateau4/b005-3/workflow.yml, engine/runtime/tests/fixture/workflow/wasm/runtime_executor/attribute_python.yaml, engine/schema/actions.json, engine/schema/actions_en.json, engine/schema/actions_es.json, engine/schema/actions_fr.json, engine/schema/actions_ja.json, engine/schema/actions_zh.json
=> feat(engine): enhance WasmRuntimeExecutor to support downloading source code from URLs

engine/CLAUDE.md, engine/runtime/examples/fixture/graphs/lod_splitter_with_dm_2.yml, engine/runtime/examples/fixture/workflow/quality-check/plateau4/01-common/workflow.yml, engine/runtime/examples/fixture/workflow/quality-check/plateau4/02-bldg/workflow.yml
=> feat(engine): quality-check workflow for bldg (WIP)

engine/Cargo.lock, engine/Cargo.toml, engine/plateau-gis-quality-checker/src-tauri/Cargo.toml, engine/runtime/action-plateau-processor/Cargo.toml, engine/runtime/action-plateau-processor/src/plateau4/domain_of_definition_validator.rs, engine/runtime/action-plateau-processor/src/plateau4/missing_attribute_detector.rs
=> test(engine): refactor engine tests (minor changes)

.github/workflows/build_deploy_api.yml
=> fix(ci): update build path for API to use correct command

engine/Cargo.lock, engine/Cargo.toml, engine/docs/mdbook/src/action.md, engine/plateau-gis-quality-checker/src-tauri/Cargo.toml, engine/runtime/action-plateau-processor/src/plateau4/domain_of_definition_validator.rs, engine/runtime/action-plateau-processor/src/plateau4/missing_attribute_detector.rs, engine/runtime/examples/fixture/graphs/plateau4/domain_of_definition_validator.yml, engine/runtime/examples/fixture/graphs/plateau4/quality-check/01-01-common.yml, engine/runtime/examples/fixture/graphs/plateau4/quality-check/01-02-common.yml, engine/runtime/examples/fixture/graphs/plateau4/xml_validator.yml, engine/runtime/examples/fixture/graphs/xml_validator.yml, engine/runtime/examples/fixture/workflow/quality-check/plateau4/02-bldg/workflow.yml, engine/schema/actions.json, engine/schema/actions_en.json, engine/schema/actions_es.json, engine/schema/actions_fr.json, engine/schema/actions_ja.json, engine/schema/actions_zh.json
=> refactor(engine): refactor port names to camelCase

engine/Cargo.lock, engine/Cargo.toml, engine/containers/worker/Dockerfile, engine/plateau-gis-quality-checker/src-tauri/Cargo.toml
=> fix(worker): correct Dockerfile to install patchelf alongside python3.11-venv

server/api/internal/usecase/interactor/cms.go
=> fix(api): remove permission checks in CMS project retrieval

engine/Cargo.lock, engine/Cargo.toml, engine/docs/mdbook/src/action.md, engine/plateau-gis-quality-checker/src-tauri/Cargo.toml, engine/runtime/action-processor/src/attribute/bulk_renamer.rs, engine/runtime/action-processor/src/geometry/bufferer.rs, engine/runtime/action-processor/src/geometry/clipper.rs, engine/runtime/action-source/src/feature_creator.rs, engine/runtime/action-source/src/file/csv.rs, engine/runtime/action-source/src/file/reader/csv.rs, engine/runtime/action-source/src/file/reader/runner.rs, engine/schema/actions.json, engine/schema/actions_en.json, engine/schema/actions_es.json, engine/schema/actions_fr.json, engine/schema/actions_ja.json, engine/schema/actions_zh.json
First batch of actions to update titles and descriptions for better user facing language:
1. **FeatureCreator** (`runtime/action-source/src/feature_creator.rs`)
2. **BulkAttributeRenamer** (`runtime/action-processor/src/attribute/bulk_renamer.rs`)
3. **Bufferer** (find in `runtime/action-processor/src/geometry/`)
4. **CsvReader** (find in `runtime/action-source/src/file/`)
5. **Clipper** (find in `runtime/action-processor/src/geometry/`)
=> refactor(docs): Update descriptions and parameter documentation for processors and sources

engine/Cargo.lock, engine/Cargo.toml, engine/docs/mdbook/src/action.md, engine/plateau-gis-quality-checker/src-tauri/Cargo.toml, engine/runtime/action-plateau-processor/src/plateau4/max_lod_extractor.rs, engine/runtime/action-plateau-processor/src/plateau4/missing_attribute_detector.rs, engine/runtime/action-plateau-processor/src/plateau4/object_list_extractor.rs, engine/runtime/action-plateau-processor/src/plateau4/udx_folder_extractor.rs, engine/runtime/action-processor/src/attribute/manager.rs, engine/runtime/action-processor/src/feature/reader/csv.rs, engine/runtime/action-processor/src/feature/type_filter.rs, engine/runtime/action-processor/src/feature/writer.rs, engine/runtime/action-processor/src/feature/writer/json.rs, engine/runtime/action-processor/src/geometry/line_on_line_overlayer.rs, engine/runtime/action-processor/src/geometry/surface_footprint_replacer.rs, engine/runtime/action-sink/src/file/excel.rs, engine/runtime/action-sink/src/file/zip.rs, engine/runtime/action-source/src/file/reader/citygml.rs, engine/runtime/action-wasm-processor/src/runtime_executor.rs, engine/schema/actions.json, engine/schema/actions_en.json, engine/schema/actions_es.json, engine/schema/actions_fr.json, engine/schema/actions_ja.json, engine/schema/actions_zh.json
Add detailed parameter documentation for various processors and extractors, improving clarity and consistency. Update package versions for plateau-gis-quality-checker and reearth-flow.
=> feat(engine): Enhance parameter documentation and update package versions

server/websocket/src/broadcast/group.rs, server/websocket/src/storage/redis/mod.rs, server/websocket/src/ws.rs
=> fix(websocket): remove empty nodes check in map JSON validation

server/api/gql/user.graphql, server/api/internal/adapter/gql/generated.go, server/api/internal/adapter/gql/gqlmodel/convert_user.go, server/api/internal/adapter/gql/gqlmodel/models_gen.go
=> feat(api): add user metadata fields including description, website, photo URL and language

engine/Cargo.lock, engine/Cargo.toml, engine/docs/mdbook/src/action.md, engine/plateau-gis-quality-checker/src-tauri/Cargo.toml, engine/runtime/action-source/Cargo.toml, engine/runtime/action-source/src/errors.rs, engine/runtime/action-source/src/file.rs, engine/runtime/action-source/src/file/czml.rs, engine/runtime/action-source/src/mapping.rs, engine/runtime/action-source/tests/czml_test.rs, engine/schema/actions.json, engine/schema/actions_en.json, engine/schema/actions_es.json, engine/schema/actions_fr.json, engine/schema/actions_ja.json, engine/schema/actions_zh.json, engine/schema/i18n/actions/en.json, engine/schema/i18n/actions/es.json, engine/schema/i18n/actions/fr.json, engine/schema/i18n/actions/ja.json, engine/schema/i18n/actions/zh.json
=> feat(engine): add CzmlReader for reading CZML files and update related components

engine/runtime/examples/fixture/workflow/data-convert/plateau4/01-bldg.yml, engine/runtime/examples/fixture/workflow/data-convert/plateau4/01-bldg/workflow.yml
The job completed successfully in the cloud. Result:
https://console.cloud.google.com/batch/jobsDetail/regions/asia-northeast1/jobs/df272162-6eff-4e50-b937-e0b1507e676e/details?invt=Ab6u4A&project=reearth-plateau
CMS:
https://cms.plateauview.mlit.go.jp/workspace/01gmsy71w8rzh3b2getz7est3p/project/01j9nk4sr4wammj0by9d5cavzk/content/01j9ntvd3trpjxcpdr40eas9qy/details/01k03zdyw07yzkw69m32hd95x0
=> fix(engine): resolve job failure in cloud environment by using `workerArtifactPath`

ui/src/components/visualizations/Cesium/index.tsx, ui/src/components/visualizations/MapLibre/index.tsx, ui/src/features/Canvas/index.tsx, ui/src/features/Editor/components/TopBar/components/HomeMenu/index.tsx, ui/src/lib/i18n/locales/en.json, ui/src/lib/i18n/locales/es.json, ui/src/lib/i18n/locales/fr.json, ui/src/lib/i18n/locales/ja.json, ui/src/lib/i18n/locales/zh.json
=> feat(ui): move attributions to cleanup UI

server/api/internal/adapter/gql/resolver_subscription.go, server/api/internal/usecase/interactor/job.go, server/api/pkg/job/monitor/monitor.go, server/api/pkg/subscription/job_subscription.go
To identfy the cause of below.
https://www.notion.so/eukarya/Job-status-is-unreliable-22216e0fb165808f9f26fdf21fbf66ac?v=22216e0fb16580aa8bdc000c8fdf9a18
ref:
https://eukarya-inc.slack.com/archives/C064TUMGNDA/p1756962579902069
=> chore(server): add logs for job status unrelible [FLOW-BE-171]

server/websocket/src/bin/websocket.rs, server/websocket/src/broadcast/group.rs, server/websocket/src/broadcast/pool.rs, server/websocket/src/conn.rs, server/websocket/src/storage/redis/mod.rs, server/websocket/src/ws.rs
=> feat(websocket): implement awareness auto-cleanup when users disconnect [FLOW-BE-210]

server/api/internal/app/app.go, server/api/internal/app/usecase.go, server/api/internal/usecase/interactor/common.go
To deal with the task below.
https://www.notion.so/eukarya/Job-status-is-unreliable-22216e0fb165808f9f26fdf21fbf66ac?v=22216e0fb16580aa8bdc000c8fdf9a18
ref:
https://www.notion.so/eukarya/Job-status-is-unreliable-22216e0fb165808f9f26fdf21fbf66ac?v=22216e0fb16580aa8bdc000c8fdf9a18&source=copy_link#26916e0fb16580c6947ac7bd28802bda
https://eukarya-inc.slack.com/archives/C064TUMGNDA/p1756962579902069
=> feat(server): make Job in-process singleton [FLOW-BE-171]

server/websocket/src/application/kv.rs, server/websocket/src/bin/websocket.rs, server/websocket/src/broadcast/pool.rs, server/websocket/src/conf.rs, server/websocket/src/domain/value_objects/conf.rs, server/websocket/src/domain/value_objects/http.rs, server/websocket/src/domain/value_objects/redis.rs, server/websocket/src/infrastructure/redis/mod.rs, server/websocket/src/infrastructure/redis/trimmer.rs, server/websocket/src/interface/http/handlers.rs, server/websocket/src/interface/http/router.rs, server/websocket/tests/ydoc.rs
- Added configuration options for Redis stream trimming: max length, max message age, and trim interval.
- Implemented methods for trimming Redis streams based on length and minimum ID.
- Updated RedisStore to read all stream data and return the last ID.
- Refactored document loading to support transactions in various handlers.
- Introduced a stream trimmer to manage Redis stream entries efficiently.
=> feat(webscoket): enhance Redis stream management with new configuration options and trimming functionality

server/api/gql/document.graphql, server/api/internal/adapter/gql/generated.go, server/api/internal/adapter/gql/resolver_document.go, server/api/internal/infrastructure/websocket/client.go, server/api/internal/usecase/interactor/websocket.go, server/api/internal/usecase/interfaces/websocket.go, server/websocket/src/application/kv.rs, server/websocket/src/broadcast/pool.rs, server/websocket/src/interface/http/handlers.rs, server/websocket/src/interface/http/router.rs
=> feat(websocket): enhance document copying functionality to include source parameter

server/api/internal/adapter/gql/gqlmodel/scalar.go
=> fix(api): update Bytes marshaling and unmarshaling to use number arrays instead of base64 encoding

server/subscriber/Dockerfile, server/subscriber/go.mod
The error occurred when the PR was merged
PR
https://github.com/reearth/reearth-flow/pull/1474
error
https://github.com/reearth/reearth-flow/actions/runs/18087617026/job/51461461478
=> chore(subscriber): update dependencies for subscriber-2 [FLOW-BE-214]

server/api/e2e/gql_import_test.go, server/api/internal/infrastructure/websocket/client.go, server/api/internal/infrastructure/websocket/dto.go
=> fix(api): update importDocument method to convert data from byte array to int array

engine/README.md
=> docs(engine): update engine/README.md

engine/Cargo.lock, engine/Cargo.toml, engine/docs/mdbook/src/action.md, engine/plateau-gis-quality-checker/src-tauri/Cargo.toml, engine/runtime/action-python-processor/src/python_executor.rs, engine/runtime/examples/fixture/tests/Cargo.toml, engine/schema/actions.json, engine/schema/actions_en.json, engine/schema/actions_es.json, engine/schema/actions_fr.json, engine/schema/actions_ja.json, engine/schema/actions_zh.json
=> feat(engine): add support for optional script and pythonfile parameters in PythonScriptProcessor

server/api/internal/infrastructure/redis/userfacinglog.go, server/api/internal/infrastructure/redis/userfacinglog_test.go, server/subscriber/internal/adapter/pubsub/user_facing_log_subscriber_test.go, server/subscriber/internal/infrastructure/redis/user_facing_log_test.go, server/subscriber/internal/usecase/interactor/user_facing_log_subscriber.go, server/subscriber/internal/usecase/interactor/user_facing_log_subscriber_test.go, server/subscriber/pkg/userfacinglog/user_facing_log.go, server/subscriber/pkg/userfacinglog/user_facing_log_test.go
Normalize UserFacingLogLevel string values to uppercase.
change displayMessage to message
ref:
https://eukarya-inc.slack.com/archives/C046GJMVD2T/p1759732140614869
=> fix(api, subscriber): normalize log level to uppercase and change displayMessage to message

engine/Cargo.lock, engine/Cargo.toml, engine/plateau-gis-quality-checker/src-tauri/Cargo.toml, engine/runtime/examples/fixture/tests/Cargo.toml, engine/worker/src/types/user_facing_log_event.rs, engine/worker/src/user_facing_log_handler.rs
As the title says, I've implemented the changes for the user-facing.log.
ref:
https://eukarya-inc.slack.com/archives/C046GJMVD2T/p1759732140614869
https://eukarya-inc.slack.com/archives/C02F1DCJ4HW/p1759735834149939
=> fix(engine): normalize log level to uppercase and change displayMessage to message
