reearth/reearth-flow

- crates/common/src/uri.rs
- crates/storage/src/operator.rs
- add HTTP protocol support to URI enum and resolve_operator function
- HTTP protocol support to URI enum 
- modify resolve_operator function
> feat: add HTTP protocol support to URI enum and resolve_operator function

- .github/dependabot.yml
- update dependabot.yml to change package directory to /worker
> chore: update dependabot.yml to change package directory to /worker

- worker/crates/action-processor/src/attribute/mapping.rs
- worker/crates/action-processor/src/feature/mapping.rs
- worker/crates/action-processor/src/geometry/mapping.rs
- worker/crates/action-processor/src/plateau/mapping.rs
- worker/crates/action-processor/src/xml/mapping.rs
- worker/crates/action-source/src/file/path_extractor.rs
- worker/crates/runtime/src/executor/execution_dag.rs
- worker/examples/plateau/attribute_reader.rs
- worker/examples/plateau/testdata/graphs/xml_validator.yml
- worker/examples/plateau/testdata/workflow/attribute_reader.yml
- worker/examples/plateau/testdata/workflow/xml_validator.yml
- worker/examples/plateau/xml_validator.rs
- Update XML validator workflow to use new XML file
- Update attribute_reader.rs to execute "xml_validator.yml" instead of
"attribute_reader.yml"
- Update xml_validator.rs to create workflow with "xml_validator.yml"
instead of "domain_of_definition_validator.yml"
- Update xml_validator.yml to use new XML file path and add additional
configuration options
- Update execution_dag.rs to fix port mapping bug
> feat(worker): Update XML validator workflow to use new XML file

- worker/crates/action-processor/src/xml/validator.rs
- worker/crates/cli/src/run.rs
- worker/crates/common/src/xml.rs
- worker/crates/runner/src/executor.rs
- worker/crates/runner/src/orchestrator.rs
- worker/crates/runner/src/runner.rs
- worker/crates/runtime/src/builder_dag.rs
- worker/crates/runtime/src/dag_schemas.rs
- worker/crates/runtime/src/executor/dag_executor.rs
- worker/crates/runtime/src/executor/execution_dag.rs
- worker/crates/runtime/src/executor/processor_node.rs
- worker/crates/runtime/src/executor/source_node.rs
- worker/crates/runtime/src/feature_store.rs
- worker/crates/runtime/src/forwarder.rs
- worker/crates/runtime/src/node.rs
- worker/crates/state/src/lib.rs
- worker/examples/plateau/helper.rs
- worker/examples/plateau/testdata/graphs/xml_validator.yml
- worker/tests/helper.rs
This commit adds the `EdgeId` type to the `Node` module in order to support routing functionality. The `EdgeId` type is defined as a `uuid::Uuid` and will be used for identifying edges in the routing process.
> feat(worker): Add EdgeId type for routing in Node module

- worker/Cargo.lock
- worker/crates/action-processor/src/feature/reader/citygml.rs
- worker/crates/action-source/src/file/reader/citygml.rs
- worker/crates/types/src/geometry.rs
- This commit adds the `bounded_by` field to the CityGML parsing logic in both the `action-source` and `action-processor` crates. The `bounded_by` field is now included in the `Entity` struct, allowing for better handling of CityGML objects with bounding information.
> feat(worker): Add bounded_by field to CityGML parsing

- schema/actions.json
- worker/crates/cli/src/run.rs
This commit adds support for reading the workflow JSON from stdin in the `run` command of the CLI. If the workflow path is set to "-", the JSON will be read from stdin. This allows users to pipe the workflow JSON directly into the command, providing more flexibility in how the workflow is provided.
> feat(worker): support reading workflow from stdin

- worker/README.md
- worker/crates/cli/src/run.rs
- worker/crates/common/src/serde.rs
- worker/crates/types/src/workflow.rs
- worker/examples/Cargo.toml
- worker/examples/plateau/attribute_reader.rs
- worker/examples/plateau/lod_splitter_with_dm.rs
The commit adds instructions for setting up the environment variable
`FLOW_VAR_cityGmlPath` in the worker README file. This variable is used
to specify the path to the cityGml file.
> feat: Add environment variable for cityGmlPath in worker README

- .github/actions/build_deploy_api/action.yml
- .github/actions/build_deploy_ui/action.yml
Because the GCR (Google Container Registry) will be decommissioned.
* [Transition from Container Registry, Google Cloud](https://cloud.google.com/artifact-registry/docs/transition/transition-from-gcr) 
> Container Registry is deprecated and scheduled for shutdown. After May 15, 2024, Artifact Registry will host images for the gcr.io domain in Google Cloud projects without previous Container Registry usage
Re:Earth Visualizer version: https://github.com/reearth/reearth-visualizer/pull/1018
> ci: migrate GCR to GAR

- schema/workflow.json
- worker/Cargo.lock
- worker/Cargo.toml
- worker/Makefile.toml
- worker/crates/cli/src/cli.rs
- worker/crates/cli/src/lib.rs
- worker/crates/cli/src/schema_action.rs
- worker/crates/cli/src/schema_workflow.rs
- worker/crates/geometry/src/validation.rs
- worker/crates/types/src/workflow.rs
This commit adds the `schema-action` and `schema-workflow` commands to
the CLI in the `worker` crate. These commands allow users to view the
action and workflow schemas respectively. The `schema-action` command
shows the schema for actions, while the `schema-workflow` command shows
the schema for workflows.
The changes include:
- Adding `schema_action.rs` and `schema_workflow.rs` modules to the
`cli` crate
- Renaming the `schema.rs` module to `schema_action.rs`
- Implementing the `SchemaActionCliCommand` struct and the
`build_schema_action_command` function
- Implementing the `SchemaWorkflowCliCommand` struct and the
`build_schema_workflow_command` function
- Updating the `Makefile.toml` file to include the new commands in the
`doc` workflow task
These changes improve the usability of the …
> feat(worker): Add schema-action and schema-workflow commands to CLI

- ui/src/features/Editor/components/BottomPanel/index.tsx
- ui/src/features/Editor/components/Canvas/components/Nodes/NoteNode/index.tsx
- ui/src/features/Editor/components/Canvas/components/Nodes/ReaderNode.tsx
- ui/src/features/Editor/components/Canvas/hooks.ts
- ui/src/features/Editor/components/Canvas/index.tsx
- ui/src/features/Editor/components/LeftPanel/index.tsx
- ui/src/features/Editor/components/OverlayUI/components/ActionBar/index.tsx
- ui/src/features/Editor/components/OverlayUI/components/Breadcrumb/index.tsx
- ui/src/features/Editor/components/OverlayUI/components/CanvasActionbar/index.tsx
- ui/src/features/Editor/components/OverlayUI/components/Infobar/index.tsx
- ui/src/features/Editor/components/OverlayUI/components/Toolbox/index.tsx
- ui/src/features/Editor/components/OverlayUI/components/index.ts
- ui/src/features/Editor/components/OverlayUI/index.tsx
- ui/src/features/Editor/components/RightPanel/index.tsx
- ui/src/features/Editor/components/WorkflowTabs/index.tsx
- ui/src/features/Editor/components/index.ts
- ui/src/features/Editor/hooks.ts
- ui/src/features/Editor/index.tsx
- ui/src/lib/yjs/useYjsStore.ts
- ui/src/lib/yjs/workflowBuilder.ts
- ui/src/routes/workspace_.$workspaceId_.project.$projectId.lazy.tsx
- ui/src/stores/index.ts
> fix(ui):  yjs init setup working with workflows, not single sets of nodes and edges

- ui/src/features/Editor/useCanvasCopyPaste.ts
Previously selected edges from the copied/cut nodes were not being deselected, therefore added similar logic of hanldeNodesChange for handleEdgesChange
> fix(ui): removed console.log and set edges to deselect on paste [FLOW-FE-167]

- CLAUDE.md
- engine/CLAUDE.md
- engine/README.md
- engine/runtime/examples/fixture/workflow/requirement/plateau4/a009-4/workflow.yml
- Add root CLAUDE.md with monorepo overview and development commands
- Add engine/CLAUDE.md with detailed workflow engine architecture
- Update engine/README.md with improved cache directory documentation
- Fix workflow fixture output filename in a009-4 example
> docs: add comprehensive CLAUDE.md documentation for monorepo

- ui/src/components/errors/ErrorPage/index.tsx
- ui/src/components/errors/index.ts
- ui/src/components/index.ts
- ui/src/errors/index.tsx
- ui/src/lib/i18n/locales/en.json
- ui/src/lib/i18n/locales/es.json
- ui/src/lib/i18n/locales/fr.json
- ui/src/lib/i18n/locales/ja.json
- ui/src/lib/i18n/locales/zh.json
- ui/src/lib/yjs/conversions/rebuildWorkflow.ts
- ui/src/main.tsx
- ui/src/routes/index.tsx
- ui/src/routes/shared.$sharedToken.lazy.tsx
- ui/src/routes/workspaces.$workspaceId_.projects_.$projectId.lazy.tsx
- ui/src/routes/workspaces.tsx
For rendering errors there was no generic message or indication to the user there is a problem. Also for any of these types of errors that occurred in the Editor it would prompt the user to revert project when it was unnecessary.
Adds a reusable generic error page and updates routes to distinguish corrupted-project errors from other failures.
- Introduces ErrorPage component under components/errors and exports it.
- Custom Errors for edge cases (ProjectCorruption)
- Fallback at root level to 404 if page route doesnt exist
- Fixed logo being a green square
Added a check for when a project is corrupted by checking the instance of the error to see if it matches the new ProjectCorruptionError if it does we can conclude it is the project corruption error where a position is not found. If this …
> fix(ui): added a generic error page for general errors [FLOW-FE-212]

- engine/Cargo.lock
- engine/Cargo.toml
- engine/containers/worker/Dockerfile
- engine/plateau-gis-quality-checker/src-tauri/Cargo.toml
- engine/runtime/action-wasm-processor/src/runtime_executor.rs
> fix(worker): add python3.11 and other dependencies to worker to support py2wasm

- engine/Cargo.lock
- engine/Cargo.toml
- engine/plateau-gis-quality-checker/src-tauri/Cargo.toml
- engine/runtime/action-processor/src/feature/reader.rs
- engine/runtime/action-processor/src/feature/reader/citygml/processor.rs
- engine/runtime/action-processor/src/feature/reader/citygml/reader.rs
- engine/runtime/action-processor/src/feature/reader/csv.rs
- engine/runtime/action-processor/src/feature/reader/json.rs
- engine/runtime/action-wasm-processor/src/runtime_executor.rs
Fix expression evaluation inconsistency for URL/path fields across file reader 
actions
Problem
File reader actions were inconsistently handling unquoted URLs in expression
fields:
- FileReader.dataset: https://example.com ✅ (graceful fallback)
- WasmRuntimeExecutor.source: https://example.com ❌ (hard error)
- FeatureReader.dataset: https://example.com ❌ (hard error)
Users had to remember which actions required quotes and which didn't, leading to
confusing errors.
Solution
Standardized all file/URL reader actions to use graceful fallback pattern:
- If expression evaluation succeeds → use evaluated result
- If expression evaluation fails → fall back to raw string value
Changes
- WasmRuntimeExecutor: Updated to use eval_scope() with unwrap_or_else()
fallback
- FeatureReader …
> fix(engine): expression fallback

- engine/runtime/action-processor/src/geometry/clipper.rs
- Add full CityGML geometry support to the Clipper action
- Support composite surfaces (MultiSurface) with recursive processing
- Handle line strings (Curve type geometries) appropriately
- Enable CityGML geometries as both clipper and candidate inputs
- Extract 3D polygons from CityGML for clipping operations
- Add recursive processing for composite surfaces (nested GML geometries)
- Handle line strings for Curve type geometries (preserved as-is since they cannot be clipped)
- Preserve CityGML metadata (materials, textures, UV coordinates) after clipping
- Add comprehensive tests for all CityGML geometry types (Solid, Surface, Curve, composite surfaces)
- Add documentation comments about 3D clipping limitations (2.5D surface clipping, not volumetric)
Added 18 tests covering:
- Basic …
> feat(engine): add CityGML geometry support, fix decimal precision for Clipper action

- server/websocket/.env.local
- server/websocket/src/broadcast/group.rs
- server/websocket/src/storage/redis/mod.rs
- server/websocket/src/ws.rs
Fixed node deletion persistence issue in WebSocket server where deleted nodes would reappear after page reload due to Redis stream replay.
1. Root Cause Analysis
- Identified that the WebSocket server was replaying ALL Redis stream updates when loading documents
- Found that deleted nodes were recreated because old creation events in Redis stream were being replayed on top of the saved GCS state
2. Implemented Proper Fix
- Added get_stream_last_id() method to capture the last Redis stream entry before GCS save
- Added trim_stream_before() method to remove Redis entries that have been incorporated into GCS
- Modified GCS save logic to trim Redis stream after successful save, keeping only new updates
3. Reverted Problematic Changes
- Reverted commit a08d6d757 that removed empty nodes …
> feat(websocket): node deletion persistence issue where deleted nodes would reappear after page reload

- server/api/internal/adapter/gql/resolver_mutation_user.go
- server/api/internal/app/auth_middleware.go
- server/api/internal/infrastructure/gql/user/input.go
- server/api/internal/infrastructure/gql/user/mutation.go
- server/api/internal/infrastructure/gql/user/query.go
- server/api/internal/infrastructure/gql/user/repo.go
- server/api/internal/infrastructure/gql/util/converter_common.go
- server/api/internal/infrastructure/gql/util/converter_user.go
- server/api/internal/infrastructure/gql/util/converter_workspace.go
- server/api/internal/usecase/interactor/user.go
- server/api/internal/usecase/interfaces/user.go
- server/api/pkg/user/mockrepo/mockrepo.go
- server/api/pkg/user/repo.go
- server/api/pkg/user/update.go
Replaced user management with accounts service for the UpdateMe API
https://www.notion.so/eukarya/Epic-Replace-user-management-in-API-with-reearth-accounts-24616e0fb16580aaa44eeb852b769a8a?source=copy_link#25a16e0fb16580e78159ed86b3a1f275
> feat(server): replace user management to accounts for UpdateMe [FLOW-BE-191]

- server/api/internal/adapter/gql/gqlmodel/convert_user.go
- server/api/internal/adapter/gql/gqlmodel/convert_workspace.go
- server/api/internal/adapter/gql/loader_user.go
- server/api/internal/adapter/gql/resolver_mutation_workspace.go
- server/api/internal/app/auth_middleware.go
- server/api/internal/infrastructure/gql/util/converter_user.go
- server/api/internal/infrastructure/gql/util/converter_workspace.go
- server/api/internal/infrastructure/gql/workspace/input.go
- server/api/internal/infrastructure/gql/workspace/mutation.go
- server/api/internal/infrastructure/gql/workspace/repo.go
- server/api/internal/usecase/interactor/workspace.go
- server/api/internal/usecase/interfaces/workspace.go
- server/api/pkg/user/user.go
- server/api/pkg/workspace/mockrepo/mockrepo.go
- server/api/pkg/workspace/repo.go
- server/api/pkg/workspace/workspace.go
**The target branch for this pull request is "feat/replace-user-management-for-updateuser".**
Replaced user management with accounts service for the CreateWorkspace API
https://www.notion.so/eukarya/Epic-Replace-user-management-in-API-with-reearth-accounts-24616e0fb16580aaa44eeb852b769a8a?source=copy_link#25b16e0fb16580daa261df3b7c413aac
> feat(server): replace user management to accounts for CreateWorkspace [FLOW-BE-191]

- server/api/internal/app/config/config.go
- server/api/internal/app/repo.go
- server/api/internal/infrastructure/gcpbatch/batch.go
This PR adds support for passing the `FLOW_WORKER_USER_FACING_LOG_TOPIC` environment variable from the API server to the Worker in Google Cloud Batch.
This is a subticket of https://github.com/reearth/reearth-flow/pull/1222
- Added `Worker_PubSubUserFacingLogTopic` config field with default value "flow-user-facing-log"
- Updated BatchConfig and job submission to pass the variable to the Worker
- Environment variable flow:
`REEARTH_FLOW_WORKER_PUBSUB_USER_FACING_LOG_TOPIC` → API → Worker as `FLOW_WORKER_USER_FACING_LOG_TOPIC`
> feat(api): Add Worker_PubSubUserFacingLogTopic to config

- server/api/internal/adapter/gql/resolver_mutation_workspace.go
- server/api/internal/app/auth_middleware.go
- server/api/internal/infrastructure/gql/workspace/input.go
- server/api/internal/infrastructure/gql/workspace/mutation.go
- server/api/internal/infrastructure/gql/workspace/repo.go
- server/api/internal/usecase/interactor/workspace.go
- server/api/internal/usecase/interfaces/workspace.go
- server/api/pkg/workspace/mockrepo/mockrepo.go
- server/api/pkg/workspace/repo.go
Replaced user management with accounts service for the UpdateWorkspace API
https://www.notion.so/eukarya/Epic-Replace-user-management-in-API-with-reearth-accounts-24616e0fb16580aaa44eeb852b769a8a?source=copy_link#25c16e0fb165807dba31f614ccd40d33
> feat(server): replace user management to accounts for UpdateWorkspace [FLOW-BE-191]

- server/api/internal/adapter/gql/resolver_mutation_workspace.go
- server/api/internal/app/auth_middleware.go
- server/api/internal/infrastructure/gql/workspace/input.go
- server/api/internal/infrastructure/gql/workspace/mutation.go
- server/api/internal/infrastructure/gql/workspace/repo.go
- server/api/internal/usecase/interactor/workspace.go
- server/api/internal/usecase/interfaces/workspace.go
- server/api/pkg/workspace/mockrepo/mockrepo.go
- server/api/pkg/workspace/repo.go
Replaced user management with accounts service for the DeleteWorkspace API
https://www.notion.so/eukarya/Epic-Replace-user-management-in-API-with-reearth-accounts-24616e0fb16580aaa44eeb852b769a8a?source=copy_link#25c16e0fb16580bf8608ccec0a4891bc
> feat(server): replace user management to accounts for DeleteWorkspace [FLOW-BE-191]

- server/api/internal/adapter/gql/resolver_mutation_workspace.go
- server/api/internal/app/auth_middleware.go
- server/api/internal/infrastructure/gql/workspace/input.go
- server/api/internal/infrastructure/gql/workspace/mutation.go
- server/api/internal/infrastructure/gql/workspace/repo.go
- server/api/internal/usecase/interactor/workspace.go
- server/api/internal/usecase/interfaces/workspace.go
- server/api/pkg/workspace/mockrepo/mockrepo.go
- server/api/pkg/workspace/repo.go
Replaced user management with accounts service for the RemoveMemberFromWorkspace API
https://www.notion.so/eukarya/Epic-Replace-user-management-in-API-with-reearth-accounts-24616e0fb16580aaa44eeb852b769a8a?source=copy_link#26116e0fb165804bb7aacc945261e438
> feat(server): replace user management to accounts for RemoveMemberFromWorkspace [FLOW-BE-191]

- server/websocket/src/conf.rs
- server/websocket/src/lib.rs
- Moved the `DEFAULT_AUTH_URL` import to be conditional based on the `auth` feature flag.
- Simplified the logic for setting the authentication URL in the configuration builder by removing unnecessary block structure.
- Ensured that the configuration remains clean and maintainable while supporting the authentication feature.
> fix(websocket): adjust configuration for authentication feature

- server/api/internal/adapter/gql/resolver_mutation_user.go
- server/api/internal/app/auth_middleware.go
- server/api/internal/infrastructure/gql/user/input.go
- server/api/internal/infrastructure/gql/user/mutation.go
- server/api/internal/infrastructure/gql/user/repo.go
- server/api/internal/usecase/interactor/user.go
- server/api/internal/usecase/interfaces/user.go
- server/api/pkg/user/mockrepo/mockrepo.go
- server/api/pkg/user/repo.go
Replaced user management with accounts service for the DeleteMe API
https://www.notion.so/eukarya/Epic-Replace-user-management-in-API-with-reearth-accounts-24616e0fb16580aaa44eeb852b769a8a?source=copy_link#27016e0fb165808cb505c64bb14fce9b
> feat(server): replace user management to accounts for DeleteMe [FLOW-BE-191]

- server/websocket/src/bin/websocket.rs
- server/websocket/src/broadcast/group.rs
- server/websocket/src/broadcast/pool.rs
- server/websocket/src/domain/value_objects/conf.rs
- server/websocket/src/domain/value_objects/sub.rs
- server/websocket/src/interface/websocket/conn.rs
- Removed the stream trimmer logic from the main function, simplifying the startup process.
- Introduced a new `ShutdownHandle` struct to manage shutdown tasks for various components in `BroadcastGroup`.
- Updated the `shutdown` method to utilize the new `ShutdownHandle` for cleaner resource management.
- Enhanced the cleanup process in `BroadcastPool` to ensure proper shutdown of broadcast groups.
> fix(websocket): fixed issue where WebSocket resources were not cleaned up correctly

- server/websocket/src/application/kv.rs
…
- Updated the `copy_document` method to ensure proper transaction management by dropping the transaction before flushing the document.
- Enhanced type constraints for the `copy_document` method to include `std::fmt::Display` for better flexibility in key handling.
> fix(websocket): improve document transaction handling in copy_document method

- server/websocket/src/broadcast/pool.rs
- Added a locking mechanism using `tokio::sync::Mutex` to ensure safe concurrent access to `BroadcastGroup` instances.
- Introduced a `locks` field in `BroadcastPool` to manage locks for each document ID.
- Updated `get_group` and `cleanup_group` methods to utilize the locking mechanism, preventing race conditions during group retrieval and cleanup.
> fix(websocket): implement locking mechanism for BroadcastGroup

- server/websocket/src/interface/http/handlers.rs
- server/websocket/src/interface/http/router.rs
already migrated to the copy and import APIs, so this one is no longer needed
> fix(websocket): remove get_latest handler from DocumentHandler 

- engine/Cargo.lock
- engine/Cargo.toml
- engine/README.md
- engine/cli/src/run.rs
- engine/plateau-gis-quality-checker/src-tauri/Cargo.toml
- engine/runtime/examples/fixture/tests/Cargo.toml
- engine/runtime/state/Cargo.toml
- engine/runtime/state/src/lib.rs
Notion task: https://www.notion.so/eukarya/Investigation-Large-intermediate-data-takes-long-time-longer-than-output-data-22216e0fb16580f9a1ede3013fe8c26d?v=22216e0fb16580aa8bdc000c8fdf9a18
I actually benchmarked several options including Parquet.
The details are below.
[https://www.notion.so/eukarya/Investigation-Large-intermediate-data-takes-long-time[…]013fe8c26d?v=22216e0fb16580aa8bdc000c8fdf9a18&source=copy_link](https://www.notion.so/eukarya/Investigation-Large-intermediate-data-takes-long-time-longer-than-output-data-22216e0fb16580f9a1ede3013fe8c26d?v=22216e0fb16580aa8bdc000c8fdf9a18&source=copy_link#27f16e0fb1658083b540e901bc4d1cc8)
The main bottleneck we were facing was the time it took to generate and process intermediate data. After benchmarking different approaches, we found …
> feat(engine): add zstd compression to jsonl intermediate data
